### ISSUE TITLE
Please consider adding a donate link and update README

### ISSUE THREAD

**Issue by preetsethi** [rxhanson/Rectangle#10]
First up: you're awesome. Thank you for doing this.

This _mostly_ fixes my issues with "resize to fullscreen" action, and as soon as I can determine enough information to write a decent issue, I plan on it. 
I am mediocre with Swift. I am god awful with Objective-C. Exploring your code is more fun and provides more insights for me.

It progressively bummed me out watching the Spectacle inactivity. I wish I could have donated / paid for that app, both to thank the author _and_ help motivate / facilitate future updates to Spectacle.

I can fully see the motivation for building and releasing this when I see what you're doing with Multitouch (which I am checking out!). Giving licenses to the contributors: you're doing this right. It's nice to see all of the above.

So I want to put my money where my mouth is! I want to thank you for your work and motivate you to keep the updates coming. **What's the best way to do that?**

If you tell me: "buy a license for Multitouch" ... I'll grab that asap.
### BUT
I sincerely request that you consider adding a Donate link. I want to put my money where my mouth is and specifically support your open-source development.

For the annoyance of having to signup for Paypal, configuring [Personal Fundraising](https://www.paypal.com/us/webapps/mpp/fundraising), and updating the README... I promise you at least $6, haha.

Hope you consider it.

**Comment by rxhanson** [comment]
Wow, thanks!

This is kind of a complicated issue, so I'm going to have to think about it for a bit. I'm not quite sure what I want to do.

My initial thought on Rectangle has been that I prefer code contributions over donations, but this would be dependent on actually having code contributions. I'd rather see Rectangle become something owned by the community, but realistically I might always be the main contributor. The code (to my eye) is pretty simple, so I'm hoping that more people will jump on board. I'm definitely willing to help people contribute.

After seeing Spectacle basically get abandoned, I can't help but wonder at which point Eric ran out of steam. He pushed out releases for 6 years. That's a pretty big time investment to just call it quits without letting a pretty large community of users and devs know. He had a donation link, too. I don't want Rectangle to end up the same way, but I guess I could see the possibility of feeling burnt out on a project if feature requests dramatically outpace community support (whether it be from code contributions or donations).

If I do decide that I'd like to accept donations, first I'll try going through the [GitHub sponsor program](https://github.com/sponsors). I might not be eligible at this point since Rectangle is kind of small, but I'll join the waitlist. Something managed by GitHub is more appealing to me since it's more tied to the code.

Again, thanks! I'll post back when I decide on a path forward.

**Comment by rxhanson** [comment]
Also, I'm interested in what you're "resize to fullscreen" issue is. Even if your issue isn't entirely clear, feel free to post it and I can provide some feedback and we can nail it down.

**Comment by borekb** [comment]
I just came here to say thank you, @rxhanson, Rectangle is really awesome, like Spectacle but without bugs and I also love the snap feature. 🙇‍♂️

**Comment by rxhanson** [comment]
@borekb, thanks for the kind words!

@preetsethi, an update on this issue:
A while ago, I did sign up for the waitlist on the GitHub sponsor program but I don't get the feeling that it would pan out anytime soon. My thought remains the same that I like the idea code contributions over donations, but I also understand that a lot people that use and potentially will use Rectangle aren't Swift devs and don't desire to be. So, I did decide to add a PayPal button but I added it to the Rectangle site ([https://rectangleapp.com](https://rectangleapp.com)).

For anyone else reading this, another way to support Rectangle is also just to get the word out. There's a huge number of window management apps out there for macOS, so it's kind of a tough market to nudge into. More users means a better product. There's also places like MacUpdate where it could use some positive ratings. Thanks all!

**Comment by preetsethi** [comment]
@rxhanson 
It's awesome to see this update! Just donated to send my thanks and put my money where my mouth is for open source development!

As I said originally, if you told me to "Buy Multitouch!" and closed this issue, I would have done that.

However, since opening this issue: I have seen your continued activity on this repo / watched you release updates for Rectangle -- this just solidified my opinion that I want to _specifically_ support and thank you for your open source work here!

You're awesome; keep it up.

**Comment by rxhanson** [comment]
Thanks so much for the donation and your support, @preetsethi! It means a lot!
