### ISSUE TITLE
"Left-Half"-Hotkey cycles through 1/2, 2/3 and 1/3

### ISSUE THREAD

**Issue by noestreich** [rxhanson/Rectangle#102]
**Thanks**
First: Rectangle is a staple on my mac, thank you for the development!

**"Left-Half"-Hotkey cycles through 1/2, 2/3 and 1/3**
Right now i only have a couple of key-combinations defined. I most often user "left-half" and "right-half". Problem is: If i hit the combination on a window which had received the command before, it switches to 2/3 and 1/3 of the screen before going back to 1/2. 

To be specific: If i hit the "Left-Half"-Hotkey (in my case <kbd>⌃</kbd>+<kbd>⌥</kbd>+<kbd>⌘</kbd>+<kbd>←</kbd>) the window goes to the left half. If i move the window now manually with my mouse and hit the "Left-Half"-Hotkey again, it does not just move back in it's half but stretches to 2/3 of the screen. I have to hit the Hotkey two times more to have it back in its half. 

**Example**
![move](https://user-images.githubusercontent.com/309419/76159252-b7df4f80-611e-11ea-93e5-128f76d980b7.gif)

I am unsure if this is expected behavior - i did not expect it and would wish for an option to deactivate it if this is indeed intended. Sometimes i also run into this behavior, while having the wrong window focused, but the moving-example is the bigger pain-point. Thanks!

- macOS version: 10.15.3 (19D76)
- Rectangle version: 0.22 (26)

**Comment by rxhanson** [comment]
Cycling through 1/2, 2/3, and 1/3 is a feature that is included because that's how Spectacle worked. You can change this behavior to cycle across monitors by checking the corresponding box in the preferences, or you can disable it using the terminal command listed on the readme: https://github.com/rxhanson/Rectangle#details-on-halves-to-thirds-subsequent-execution-of-half-and-quarter-actions

I'm guessing that you have unchecked the box for the snap areas (see https://github.com/rxhanson/Rectangle/issues/46 for the issue on a move/resize not resetting the cycle).

**Comment by noestreich** [comment]
Oh, i did not know this. Thank you. 

The solution: 

> This behavior can be disabled with the following terminal command:
> `defaults write com.knollsoft.Rectangle subsequentExecutionMode -int 2`
>
