### ISSUE TITLE
new v0.65 won't launch on 10.13.6

### ISSUE THREAD

**Issue by zafcom** [rxhanson/Rectangle#1050]
Soon after an auto-update do v0.65 I noticed that the app won't launch on login, and will refuse to launch even manually. It simply does nothing. No window is created, no menu, no taskbar icon... nothing. No process entry is seemingly created in Activity Monitor.

- [X] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 10.13.6
Rectangle version: 0.65
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): Rectangle won't open, so... no Logs!

**Comment by rxhanson** [comment]
Thanks, looks like the shortcut recorder is causing a crash.

**Comment by rxhanson** [comment]
Ok, you can download a new version of 0.65 and it should work (I tested it and it works for me).

https://github.com/rxhanson/Rectangle/releases/tag/v0.65

Normally I would increment the version here, but this is a rare scenario where I think that would make it more confusing - there's no need for users to update to it, unless you're on 10.13 and it's broken anyway so you can't update it from there.

As an aside, this marks the end of being able to use MASShortcut and still support v10.13 for Rectangle. In the next release, I will have to migrate away from it so as to keep Sparkle up to date (it makes more sense to switch to the Sindre Sorhus Keyboard Shortcuts library, written in Swift, rather than try to maintain MASShortcut).

**Comment by Amndeep7** [comment]
If you're not making a new release, can you update the Brew formula as well?  The difference in SHAs is causing it to panic.

SHA from the updated release:

```
$ openssl sha256 < Downloads/Rectangle0.65.dmg
2b2ac56512a54c18f1f55067944a901c35513c616c27db828bdd6122d2885575
```

Brew warning:

```
$ brew upgrade --greedy
==> Upgrading 1 outdated package:
rectangle 0.64,70 -> 0.65,71
==> Upgrading rectangle
==> Downloading https://github.com/rxhanson/Rectangle/releases/download/v0.65/Rectangle0.65.dmg
Already downloaded: /Users/my_username/Library/Caches/Homebrew/downloads/6945c7e7b721626562ea139d741f3e692949d14af40061ea30ce0d02891fb677--Rectangle0.65.dmg
==> Purging files for version 0.65,71 of Cask rectangle
Error: rectangle: SHA256 mismatch
Expected: d8796a71fe231200277c09101d8e8172eeacb6b90e300def1bbc282bd1623b53
  Actual: 2b2ac56512a54c18f1f55067944a901c35513c616c27db828bdd6122d2885575
    File: /Users/my_username/Library/Caches/Homebrew/downloads/6945c7e7b721626562ea139d741f3e692949d14af40061ea30ce0d02891fb677--Rectangle0.65.dmg
To retry an incomplete download, remove the file above.
```

**Comment by rxhanson** [comment]
Ah, didn't think about the brew checksum.

Looks like it's stuck on this: https://github.com/Homebrew/homebrew-cask/pull/139810

This is probably the only time I'll ever update a release in this way, but good to know if it ever happens again.
