### ISSUE TITLE
When dock is on the side, resizing to halves do not work correctly

### ISSUE THREAD

**Issue by bojomojo** [rxhanson/Rectangle#106]
I am on Catalina,
when the dock is on the right hand side for example, when I move a window to the right half, it is resized to the exact half of the screen size (not the remaining usable space (size - dock)).
Now, if I move another window to the left half, there is an area that overlaps between both windows.

**Comment by rxhanson** [comment]
I’ll need some logs and screenshots.

**Comment by alexchamberlain** [comment]
I have a similar issue with the dock at the bottom. If I have an external screen and move the dock onto it, then Rectangle will resize windows behind the Dock. Restarting Rectangle doesn't fix it.

**Comment by rxhanson** [comment]
@alexchamberlain, your issue is actually a macOS issue (which is why you see it even after restarting Rectangle). It's an issue that was posted for Spectacle, too, and there's nothing from a 3rd party perspective that can be done about it. I haven't filed the bug with Apple but I'll post back here if I get around to it.

**Comment by rxhanson** [comment]
Housekeeping closing this one out since there's no response from @bojomojo.
