### ISSUE TITLE
Rectangle v0.65 is not managing Chrome browser.  It is working for other windows.

### ISSUE THREAD

**Issue by pmeharg** [rxhanson/Rectangle#1076]
I noticed just recently that Rectangle has stopped working with Chrome browser.  I had been working for quite some time.

Chrome version: Version 110.0.5481.100 (Official Build) (arm64)

macOS version:Ventura 13.2.1
Rectangle version:v0.65
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):

**Comment by rxhanson** [comment]
This typically means that Chrome has stopped responding to the Accessibility API that Rectangle uses to move/resize windows. Unfortunately, there's nothing that Rectangle can do when this happens. It's usually fixed by restarting Chrome, but if the issue persists then you'll want to report it to the Chrome team.

**Comment by theodesp** [comment]
Experiencing the same issue with Chrome.

**Comment by pdr** [comment]
Restarting Chrome worked for me.
