### ISSUE TITLE
Adding defaults for screen margins 

### ISSUE THREAD

**Issue by nicoladefranceschi** [rxhanson/Rectangle#113]
For instance, here:

https://github.com/rxhanson/Rectangle/blob/9c8066c6aa6b3cc381ae7d5ef83be777d7cdc6af/Rectangle/Snapping/SnappingManager.swift#L279

I would like to suggest to use "defaults" values for the margins, in order to be able to change it without recompiling.

``` swift
if loc.y <= frame.maxY && loc.y > frame.maxY - Defaults.marginBottom.value { 
```

I would probably set it to something more than 5, like 50 or something (I'd like to try out some values) because I use multiple monitors and 5 is too small and require to much precision when dragging.

Let me know  😉

thanks

**Comment by rxhanson** [comment]
Right, that makes sense to me. Probably just one variable for all, or would you actually set different margins per edge? There would be some weirdness with getting close to the corners if the values are high enough, as in, having to pick which snap area you choose if you're in both. Provided that gets worked out somehow, I'd most likely accept a PR for it (it'll take a long time before I can get to it).

**Comment by nicoladefranceschi** [comment]
I can work on it.

I was thinking multiple values because for instance at the top there is the menu bar, so I could use a greater value. Personally I would make 4 variables, this will be a "pro" feature that must be enabled in the terminal, so I don't know how many people will use it, so giving more flexibility is better imo.
What do you think?


I see now that in some places there is "25"..

https://github.com/rxhanson/Rectangle/blob/9c8066c6aa6b3cc381ae7d5ef83be777d7cdc6af/Rectangle/Snapping/SnappingManager.swift#L209

or event 150

https://github.com/rxhanson/Rectangle/blob/9c8066c6aa6b3cc381ae7d5ef83be777d7cdc6af/Rectangle/Snapping/SnappingManager.swift#L243


These could actually be a "delta" value to add to the default, for instance 
```swift
 Defaults.marginTop.value + 150
```

**Comment by rxhanson** [comment]
Multiple values is fine with me. 

The values other than 5 are for the other dimension that you're not concerned with for this change, for example the 150 is the value for doing top/bottom half instead of right/left half when you're dragging to the side edge. So, no need to have the delta.

I'll go ahead and apologize for magic numbering and ugly code here :) I'll add it to my TODO to fix the magic numbers.

I would prefer to have all of these Defaults values that you add in have the initial value of 5 if it the read in value is 0 (which is what NSUserDefaults will give you when it's a number that's not configured).

**Comment by nicoladefranceschi** [comment]
PR:
https://github.com/rxhanson/Rectangle/pull/114

Personally, i use:
```bash
defaults write com.knollsoft.Rectangle marginBottom -float 100
defaults write com.knollsoft.Rectangle marginTop -float 20
```

(I have two screens, one above the other)

**Comment by rxhanson** [comment]
PR merged, so this will be in the next release.
