### ISSUE TITLE
Feature Request - Disable Rectangle Mode

### ISSUE THREAD

**Issue by lkarthee** [rxhanson/Rectangle#117]
**Problem Description:** 

- Window management apps have become indispensable, but they override many keyboard shortcuts.

-  It is a pain to remap conflicting shortcuts in every app. 

- Window reorganization is an essential but occasional activity. Everyone use window management apps to reorganize windows while primarily using some application.

-  In Xcode and Sublime Text, _find and replace_ keyboard shortcut is `CMD + ALT + F`, but Rectangle uses it to _maximise window_. I cannot use the shortcut until I remap Rectangle or Xcode. 

- There is a feature Ignore 'FrontApp' in the Rectangle but there is no shortcut to toggle it. User has to enable and disable for individual apps.

 **Solution - 'Disable Rectangle' feature which disables window action shortcuts** : 

1. This disables rectangle and frees up all the window management shortcuts. 
2. Add a keyboard shortcut `F12` to toggle Disable Rectangle functionality.
3. Add a keyboard shortcut `CTRL + F12` to toggle Ignore <Current App> functionality.
4. Show disabled status in the status menu.
5. Able to remap shortcuts in the Preference window.
6. If this feature is advanced functionality, it can be disabled by default and allow users to enable it through preferences.

I have implemented this functionality (except advance functionality )  in this pull request - https://github.com/rxhanson/Rectangle/pull/116 . This PR is just to demonstrate the utility of the features.

Disabled Status Item
![RectangleStatusItemDisabledTemplate48](https://user-images.githubusercontent.com/2712395/78527371-4c120480-77fa-11ea-8e0c-91c8e7a96a63.png)

Menu with Disable Rectangle

![disable-rectangle-menu](https://user-images.githubusercontent.com/2712395/78527250-005f5b00-77fa-11ea-94be-3615b957fc45.png)

Remap Disabled Shortcuts in Preferences pane
![shortcuts-remap](https://user-images.githubusercontent.com/2712395/78527511-b460e600-77fa-11ea-9b55-483e9e481f80.png)

**Comment by rxhanson** [comment]
I appreciate the time that you've put into this one, and I can definitely see the usefulness of this feature, but I don't think I have a desire to pull this into Rectangle. I'll take some time to explain from my perspective.

First, the Spectacle defaults are not good in my opinion because there's a decent amount of shortcuts that are used elsewhere. I don't use them, nor do I recommend them. It is an unfortunate relic of building a piece of software that is meant to be a direct drop in replacement for something that has a really large existing user base. Rectangle was built before Spectacle was officially discontinued, so those defaults exist merely to gain traction from Spectacle users that noticed Spectacle had not been maintained in ~2.5 years. My recommendation is to execute the terminal command outlined in the README: https://github.com/rxhanson/Rectangle#keyboard-shortcuts to use the Magnet shortcuts. I've had plans to change those defaults (or determine them dynamically if Spectacle is installed on your machine), but it's a hard change to make right now when a lot of Spectacle users are still continuing to make the switch.

If any of the Magnet shortcuts overlap with something from another app, I suggest just changing the Rectangle shortcuts again to something else until you get something that's not used anywhere else that you care about. That's entirely the reason that they are configurable in the first place. A lot of people seem uptight about changing shortcuts and in my opinion it's not that big of a deal to train yourself a different shortcut here or there, especially for window management since for most those are the most used shortcuts. When I've retrained myself, it takes maybe a day where it's kind of annoying and then it's not a big deal. To me, that's a better end result than memorizing an additional keyboard shortcut for disabling keyboard shortcuts so that I can use those same keyboard shortcuts to do something else in a specific app. If you were to frequently disable Rectangle entirely, then to me that means you just have a bad configuration of Rectangle shortcuts.

I'm sure there's a decent amount people that disagree with me, for which I think your fork is a good thing to have around. 

Again, I appreciate that your time and effort, and I apologize that I'm sure this isn't the answer you were looking for.

**Comment by lkarthee** [comment]
Thank you for building and maintaining Rectangle. 

I did not try out alternateDefaults (Magnet) shortcuts - will do it now. 

After reading your explanation - I strongly feel the onboarding screens of Rectangle should have a screen where user chooses between what you feel are best or Spectacle defaults. There should be a way to switch to alternateDefaults keybindings through Preference pane. 

Regarding Ignore <App> functionality, there should be a way to view and delete currently ignored apps. 

Status Bar Icon of Rectangle should reflect if it is currently ignoring the app due to user preference. 

Thank you again for taking time and explaining what you feel.

**Comment by AlJohri** [comment]
@rxhanson just wanted to chime in that I'm really looking forward to the Magnet defaults becoming the actual defaults or at least a slightly easier interface for switching to the alternate defaults. It's not hard to run the terminal command but slightly annoying to google "rectangle github" everytime I set up a new computer to find the command to copy paste. Also not a great experience for new users to whom I recommend rectangle and then need to have them do this slightly unorthodox step.

**Comment by rxhanson** [comment]
@lkarthee @AlJohri thanks for the feedback. I'll plan on building in an onboarding screen in the next release, since I think that gives us the best of both worlds. 

My current plan is that I'm going to have the two choices, Spectacle and non-Spectacle, and in addition to setting the default shortcuts, the 1/2 - 2/3 - 1/3 cycle will be only enabled at the start if you select the Spectacle path.

**Comment by rxhanson** [comment]
https://github.com/rxhanson/Rectangle/releases/tag/v0.25

**Comment by rxhanson** [comment]
Closing this one out, but feel free to keep the conversation going if needed.
