### ISSUE TITLE
Double arrow shortcut support

### ISSUE THREAD

**Issue by pasteley** [rxhanson/Rectangle#118]
Missing an option to set multiple arrow keys as a hotkey,  e.g. **← ↑ ⌘ ⌃**  for upper left side of the screen

**Comment by rxhanson** [comment]
This is something that I've given some thought to, but it's not something I'm looking to add in to Rectangle at this time. 

The keyboard shortcut recorder (MASShortcut) uses Apple's Carbon API to register hotkeys within the system. That API contains the restriction where only one key and any combination of modifiers can be registered within a hotkey. So, in order to change that behavior, we'd be basically creating a new shortcut recorder or heavily modifying MASShortcut to accept multiple keys. After we have a way to record the keys, we would need to listen to all keypresses from a user, and then act when there's a match.
