### ISSUE TITLE
rectangle no longer working on Outlook for Mac windows

### ISSUE THREAD

**Issue by wizkidr0b** [rxhanson/Rectangle#1208]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

Microsoft Outlook for Mac Version 16.74.1
Outlook has the "new outlook" item checked in the menu
For some reason on this new macbook that has a new OS and probably a new version of MS Outlook for Mac, the windows are not allowed to be affected by rectangle.  I hear a click/beep and the logs say "Failed to find frontmost window"
Other Microsoft Office products are working fine.

macOS version: 13.3
Rectangle version: 0.69 (75)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 
2023-07-20T21:04:38-05:00: Unable to obtain the accessibility element with the specified attribute at mouse location
2023-07-20T21:04:38-05:00: Failed to find frontmost window.
2023-07-20T21:04:38-05:00: Unable to obtain the accessibility element with the specified attribute at mouse location
2023-07-20T21:04:43-05:00: Failed to find frontmost window.
2023-07-20T21:04:45-05:00: Failed to find frontmost window.

**Comment by rxhanson** [comment]
Thanks for reporting with logs.  

Try restarting Outlook.

Whenever there is a singular app not responding to the accessibility API on behalf of Rectangle, unfortunately it's most likely that the issue is with the app not responding rather than with Rectangle.

Typically, this happens on cross platform apps or Electron/Chrome based apps. 

If restarting Outlook does not work, then my recommendation is to file an issue with the Outlook team.

**Comment by wizkidr0b** [comment]
recording of the issue
[https://app.screencast.com/wygR1vVwg9MDR](url)

**Comment by wizkidr0b** [comment]
restarting outlook fixed the issue.  thank you for the prompt replies.  i thought that I had already tried restarting both the app and the machine as this is a fairly new laptop for me.  cheers!  feel free to close or I'll attempt to close with comment.  Thanks again!
