### ISSUE TITLE
Rectangle incompatible with list component in System Settings

### ISSUE THREAD

**Issue by Jerry23011** [rxhanson/Rectangle#1223]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 13.5
Rectangle version: v0.69(75)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): Empty

### Description
In System Settings.app, some lists will shatter when clicking on them when Rectangle is enabled, quitting Rectangle will temporarily resolve this issue.

In `General -> Login items` and `Keyboard -> Text Substitution`, the lists would shutter when clicking on different items. (Please see screen recording below)

#### Screen Recordings

https://github.com/rxhanson/Rectangle/assets/89069957/bf5d315c-c5a6-48c7-afa0-e7139fd27705

https://github.com/rxhanson/Rectangle/assets/89069957/a6fc8243-6e1c-4558-99a3-71fe4495d9fc

**Comment by rxhanson** [comment]
Thanks for reporting. 

I can't reproduce this, so it could be something that is caused by a unique mixture of variables on your machine. I suspect if you disabled snap-by-dragging, the issue would go away. If this is the case, then there's not really anything that could be done to fix this within Rectangle, other than provide a better way to ignore System Settings for snap-by-dragging.

I'm getting ready to draft another release, and my plan is to make it easy to disable the snap-by-dragging for an app, System Settings in this case.

**Comment by Jerry23011** [comment]
> I suspect if you disabled snap-by-dragging, the issue would go away.

Yes, it does go away when I disabled snap-by-dragging, thanks for suggesting :)

**Comment by Jerry23011** [comment]
Hi @rxhanson,

I can confirm that as soon as I ignore System Settings in v0.70, this issue goes away, thank you.
