### ISSUE TITLE
Extreme lag in Jetbrains IDEs

### ISSUE THREAD

**Issue by risalfajar** [rxhanson/Rectangle#1224]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Ventura 13.4
Rectangle version: 0.69 (75)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 
```
2023-08-03T15:42:29+07:00: AX sizing proposed: (1920.0, 993.0), result: (1920.0, 993.0)
2023-08-03T15:42:29+07:00: AX position proposed: (0.0, 25.0), result: (0.0, 25.0)
2023-08-03T15:42:29+07:00: AX sizing proposed: (1920.0, 993.0), result: (1920.0, 993.0)
2023-08-03T15:42:29+07:00: maximize | display: (0.0, 62.0, 1920.0, 993.0), calculatedRect: (0.0, 25.0, 1920.0, 993.0), resultRect: (0.0, 25.0, 1920.0, 993.0), srcScreen: PHL 243V7 (1), destScreen: PHL 243V7 (1), resultScreen: PHL 243V7 (1)
```

IDE tested: Web Storm, Android Studio

When Rectangle is running, it makes these IDEs pretty slow and laggy. I've tried to ignore the IDE, but it doesn't work, it can still be snapped and laggy. The lag only gone after I quit Rectangle and then move/resize the IDE window manually.

The funny thing is, the lag is gone when I tried to record my screen, so I record it using my phone instead:
https://drive.google.com/file/d/1TLt-b-4KF2bRDorFXppbKHlIMqpMuMdN/view?usp=sharing

**Comment by rxhanson** [comment]
I use Pycharm a lot, and I never have this issue. Do you use any plugins in your IDEs that might be sensitive to clicking?

Ignoring an app doesn't also ignore drag snapping by default. There's a way to do this with a terminal command, but it's kind of clunky right now. The reason that it doesn't work this way is because of an ambiguity that exists with frontmost apps and dragging windows that are not frontmost, but maybe it makes sense to reassess what the default behavior is here anyway.

I'm getting ready to draft a new release, and I'll either add a better terminal command way to configure this behavior or adjust the default behavior. 

I suspect that there's something unusual about your setup, since there are a lot of users that use Rectangle & jet brains IDEs, I can't reproduce it, and you're the first to report this.
