### ISSUE TITLE
When holding down a keyboard shortcut such as 'Smaller' or 'Larger', Rectangle only does it once

### ISSUE THREAD

**Issue by altosaar** [rxhanson/Rectangle#123]
macOS version: 10.15.4
Rectangle version: 0.25

 (expected behavior: keep making a window smaller/larger while key is pressed -- this works in other Mac apps for other shortcuts, and I have my key repeat on very low so it is a bit jarring to need to press smaller/larger many many times on a 32" monitor instead of holding down a keyboard shortcut)

**Comment by rxhanson** [comment]
I would definitely consider a pull request for this, but I don't have plans to implement it at this time so I'm going to close it out.

**Comment by billvog** [comment]
It'd be great if we could have that 🙂

**Comment by rxhanson** [comment]
In short: I do have plans to bring this to Rectangle, but it requires other pieces to fall into place and I don't have a timeframe for when I will get to it. It could be a while.

This is currently implemented in [Rectangle Pro](https://rectangleapp.com/pro) (paid). The foundation for this capability is best implemented as part of the shortcut library that Rectangle uses (MASShortcut). I have rewritten that shortcut library in Swift to make it more maintainable and added the necessary foundation to that library, and my plan is to make my rewrite open source in order to incorporate it into Rectangle. It will take some time and effort to get the rewritten library into a state I feel comfortable making open source.
