### ISSUE TITLE
Feature request discussion: Move all windows of an app

### ISSUE THREAD

**Issue by maxsz** [rxhanson/Rectangle#129]
I think it would be great to have the option to simultaneously move all windows of an application.

**Comment by rxhanson** [comment]
Thanks for the feedback!

In order for this to be implemented, Rectangle would have to keep track of all of the accessibility elements of all the windows. Currently Rectangle only grabs the frontmost window accessibility element when a shortcut is executed. There's no mechanism built into the accessibility API to grab all the windows, so there is some complexity in adding such a feature. One would have to use the Carbon API to determine the position of all windows, then get the accessibility elements for each window that's currently not obscured by any other windows. The list containing all of the window accessibility elements would have to be updated continuously to ensure that all of the windows for an app are accounted for, and there's possibility that some windows wouldn't be included, which would lead to some confusing behavior. In addition to managing the list of accessibility elements for windows, Rectangle would also have to be adjusted to perform multiple window actions for a single shortcut execution. This is doable, but would also require a decent amount of work and add some complexity to the app.

This feature isn't really something I would consider adding into Rectangle, due to the amount of complexity it would add to the app. But, if someone does prove my assumptions wrong and finds a simple way to add it in, then I could see changing my mind.
