### ISSUE TITLE
Please add a keybroad shortcut to minimize（or hide）all windows

### ISSUE THREAD

**Issue by liyuxi** [rxhanson/Rectangle#130]
like Button in the lower right corner of Microsoft Windows。most time ,when there are many windows，backing to the desktop is very difficult. could Rectangle provide a shortcut to achieve it？

**Comment by rxhanson** [comment]
The closest you're going to get built into mac aside from the trackpad five finger spread gesture  is "command + option + h + m". 

This isn't something I have plans to make as a configurable option in Rectangle.

**Comment by strafe** [comment]
I'd love to see this as well, it's extremely frustrating that <kbd>Command</kbd> + <kbd>Option</kbd> + <kbd>H</kbd> doesn't hide the focused window (switching to Finder first is still an extra step) and <kbd>F11</kbd> is just not the same.

@rxhanson just curious, there's no particular reason an app couldn't do this right? e.g. The same behaviour as the aforementioned shortcut but also hiding the final window as well, leaving Finder focused.

**Comment by rxhanson** [comment]
@strafe The mentioned "command + option + h + m" will minimize the frontmost window as well (obviously not the same as hiding all, though).

There's ways to achieve this as a 3rd party app, but it doesn't really fit into the scope of Rectangle.

**Comment by ibash** [comment]
Have been looking for this functionality and thought it would fit well in rectangle. I think of rectangle as a window management application, which includes minimizing/hiding windows.

If rectangle had this, I'd use it multiple times per day before each context switch and zoom call. A typical workflow for me when starting a new task or meeting is:
1. Minimize all windows
2. Unminimize relevant windows
3. Use rectangle to arrange them

**Comment by rxhanson** [comment]
@ibash Thanks for the additional feedback. I agree that from an outside perspective, this would appear to fit into an application like Rectangle. To be clear on why I claimed it doesn't:
* If there are ways to do something provided by the OS, then I will typically yield to the OS rather than implementing my own version of something. In this case, there is potential for a solution that users might like better, but there are further limitations.
* Minimizing/hiding all as a 3rd party would likely rely on something like iterating through all open applications and either using the accessibility API to "click" the minimize button or executing keystrokes (cmd+m or cmd+h) in the event that the minimize button does not exist or is not enabled. This isn't a huge deal to implement, but it carries assumptions that this type of behavior or these shortcuts won't change or will be the same for all users. If the shortcuts did change, then there is some annoying maintenance burden (the less of this in a commonly used app, the better). Right now, Rectangle doesn't execute keystrokes. While it's not a lot of code to add that in, this can lead down a slippery slope of what type of behavior Rectangle is intended for. 
* I purposefully keep Rectangle slim, and I see it as a feature of the app.
* This behavior is somewhat of an outlier in Rectangle, since all of the window actions in the UI are built for individual windows. In the UI, this wouldn't quite fit in on the shortcuts tab, and the settings tab has a decent amount of settings already in it. An additional item here or there isn't a big deal, but it adds up pretty quick and I have to strongly discern what makes it in so it doesn't turn into a mess.

With that said, I will merge good pull requests that don't add to the UI (at least until there is significant demand - an example being Todo mode). If users want functionality enough that they are willing to contribute it (or if there are a ton of users asking for something), then that's typically a good sign that it's worth being there, hidden behind Terminal commands at first cut.

As an aside, it's on my todo list to add a checkbox to the "Applications" groups in Rectangle Pro to allow a configuration to unminimize windows in an application group. I don't have a timeline for when I would get to it, though.

**Comment by strafe** [comment]
@rxhanson so there's no API to hide windows? If not and Rectangle just sent shortcuts I'm not sure it would even work... If you open a few windows and press `Cmd+H` the last one will often refuse to hide, sometimes making the _"Tink"_ sound. I found a few threads of people complaining about this but no documentation as to why it happens or a solution

**Comment by rxhanson** [comment]
@strafe, there is an API to hide windows, and I use it Rectangle Pro; sorry for leaving that out. MacOS has a limitation (or rather, it's just the way it works) where one app is always in focus / not hidden, and that's why you could get the "tink" sound. I updated my last comment to reflect this. I'm not convinced to reimplement cmd + option + h + m for the sake of configuring the shortcut for it in Rectangle. Adding "minimize all" or some other way that's hidden behind terminal command is fine with me, if anyone wants to add it in.

**Comment by strafe** [comment]
@rxhanson That shortcut seems to hide all windows and minimise the current one, kinda drives me nuts since I hate minimising all together and certainly hate mix and matching the two behaviours. Do you happen to know if that API obeys the unable to hide the active window?

**Comment by rxhanson** [comment]
@strafe Yes, it is unable to hide the last active window. I built the functionality real quick to test it out and make sure.

**Comment by KoljaL** [comment]
Thank you and great app, by the way :-)

I would love to have:

<kbd>ctrl</kbd> + <kbd>↑</kbd>: maximize active window
<kbd>ctrl</kbd> + <kbd>↓</kbd>: minimize active window
<kbd>ctrl</kbd> + <kbd>←</kbd>: last active window
<kbd>ctrl</kbd> + <kbd>→</kbd>: oldest active window

maybe this app is the right one

**Comment by prassanna-ravishankar** [comment]
`cmd` + `m`

**Comment by rxhanson** [comment]
FYI, there is now an action in Rectangle Pro's stash functionality to "Stash All" windows. The stash feature works by putting windows on the edges of the screen, effectively hiding them. I still don't have plans to add this behavior to Rectangle.

**Comment by nicoandmee** [comment]
> FYI, there is now an action in Rectangle Pro's stash functionality to "Stash All" windows. The stash feature works by putting windows on the edges of the screen, effectively hiding them. I still don't have plans to add this behavior to Rectangle.

Can stash be triggered via deeplink? As in something like `open -g "rectangle-pro://execute-action?name=stash"`. All the dimension layouts are listed but some of these features are missing.
