### ISSUE TITLE
Page search input in Chrome is moved around instead of the application window

### ISSUE THREAD

**Issue by carstena** [rxhanson/Rectangle#1303]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Sonoma 14.1.1
Rectangle version: 0.75 (81)

The page search input in Chrome is moved around instead of the application window. This only occurs when the input has focus.

https://github.com/rxhanson/Rectangle/assets/1830977/cd084e7f-54e1-4585-9f70-429b55333ddb

**Comment by rxhanson** [comment]
Thanks for reporting. Typically I don't make special cases in Rectangle, and this is a scenario where Rectangle is working as intended. From this perspective, it is a Chrome implementation detail that this search bar window is moved around via the macOS accessibility API. My recommendation is to report this to the Chrome team. 

With that said, I'm not opposed to merging a pull request that makes Rectangle account for this, but I wouldn't have it enabled by default since special cased behavior on other apps is inherently fragile.

**Comment by kamronbatman** [comment]
This might be more pervasive than just this particular issue. I have been having issues with chrome/chromium for a month now where I lose the ability to use keyboard shortcuts, sometimes to single click, click and drag, etc. I have since turned off rectangle, and I haven't had a problem since. I'll report back if this ends up being a red herring.
