### ISSUE TITLE
Rectangle checks for updates too often, maybe configurable update frequency?

### ISSUE THREAD

**Issue by stgarf** [rxhanson/Rectangle#14]
I use Little Snitch and Rectangle prompts me to check for updates too often (seems daily). Ideally this is a configurable frequency with the ability to disable update checking totally.

BTW, nice work. Great Spectacle replacement since it hasn't been updated in quite a bit :)

**Comment by rxhanson** [comment]
Thanks for using Rectangle and reporting this. I don't know if I'll add in a configuration for the frequency, but better controls for disabling the update check are necessary at a minimum. That'll be something to queue up for next release.

The frequency does default to 1 day, and you should be able to configure it via terminal as follows: 
`defaults write com.knollsoft.Rectangle SUScheduledCheckInterval -float <time in seconds>`

Rectangle uses Sparkle, so [these plist settings](https://sparkle-project.org/documentation/customization/) can be overwritten via NSUserDefaults.

This is actually something that affects the server more than a user - a request that pulls back a 302 once a day is pretty minimal impact to a user, unless Little Snitch is bringing your attention to it haha. 

Perhaps I'll default it to check every 2 days instead of 1 day in a future release.

**Comment by stgarf** [comment]
Thanks! Yea, Little Snitch is a local firewall (via kernel module) that prompts you to allow or deny internet outbound and inbound internet connections. I've found that Rectangle prompts me every day for internet access yet updates for Rectangle are not posted at such a frequency to warrant such a check.

![Screen Shot 2019-09-27 at 10 22 06 AM](https://user-images.githubusercontent.com/1694002/65788953-213f4900-e111-11e9-84e5-8e7b4626484d.png)

The developer of LittleSnitch also implemented functionality that'll read a bundled `Internet Access Policy` if it's provided in the `Resources` folder. I'd be really interested in seeing Rectangle implement this. Here's the [developer documentation](https://help.obdev.at/littlesnitch/ra-developers).

Using the plist, I've defaulted Rectangle to check at a more reasonable 7 days:

```shell
$ defaults read com.knollsoft.Rectangle
{
    "NSStatusItem Preferred Position Item-0" = 667;
    "NSWindow Frame SUUpdateAlert" = "970 768 620 392 0 0 2560 1417 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2019-09-26 23:21:44 +0000";
    SUSendProfileInfo = 0;
    SUUpdateRelaunchingMarker = 0;
    launchOnLogin = 1;
    subsequentExecutionMode = 0;
}

$ defaults write com.knollsoft.Rectangle SUScheduledCheckInterval -float 604800

$ defaults read com.knollsoft.Rectangle
{
    "NSStatusItem Preferred Position Item-0" = 667;
    "NSWindow Frame SUUpdateAlert" = "970 768 620 392 0 0 2560 1417 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2019-09-26 23:21:44 +0000";
    SUScheduledCheckInterval = 604800;
    SUSendProfileInfo = 0;
    SUUpdateRelaunchingMarker = 0;
    launchOnLogin = 1;
    subsequentExecutionMode = 0;
}
```

**Comment by rxhanson** [comment]
Thanks for the link to Little Snitch's dev documentation! I will definitely add that in to the next release.

**Comment by rxhanson** [comment]
v0.7 has some changes related to this issue: 
There's a checkbox for disabling automatic update checking.
The default value for SUScheduledCheckInterval is 2 days.
I followed the dev docs for little snitch, so it should have what it needs to provide some info now.

Closing this one out, but feel free to reopen if any of those items aren't working as expected.

**Comment by stgarf** [comment]
Awesome, thanks! I'll update and test it out over the next few days!

>

**Comment by stgarf** [comment]
@rxhanson Lovely, it's working thanks!

![Screen Shot 2019-10-11 at 6 00 22 PM](https://user-images.githubusercontent.com/1694002/66692258-79b63080-ec51-11e9-8600-efe1e7a67faf.png)
