### ISSUE TITLE
Rectangle behaves weirdly with Brave’s Vertical tabs

### ISSUE THREAD

**Issue by ShakeSphereStuff** [rxhanson/Rectangle#1420]
I’m not sure if this is Brave’s or Rectangles or Apple’s fault, yet when I have vertical tabs and I rearrange them between different desktops, the vertical tabs can bleed onto other windows and switches me back to the active desktop once clicked upon

**Comment by rxhanson** [comment]
My initial thought is that this is Brave's responsibility. If you disable drag to screen edge snapping in Rectangle, do you still experience this? That's the only thing in Rectangle that affect clicking in another app, but even then the only path forward is to get it fixed by the other app or disable the feature in that app causing the issue or ignore that app in Rectangle.

**Comment by ShakeSphereStuff** [comment]
I disabled both “Snap to window by dragging” and “Restore window size when unsnapped” yet they both didn’t fix the problem, I assume that this then must be braves problem

**Comment by rxhanson** [comment]
Unfortunately, I don't think there's anything that makes sense to adjust within Rectangle, so I'm going to close this one out.
