### ISSUE TITLE
A window was not controlled as I want

### ISSUE THREAD

**Issue by aslibdnw** [rxhanson/Rectangle#145]
macOS version: Mojave 10.14.6 (18G103)
Rectangle version: 0.25 (29)
I encountered a problem when using a rectangle. For example, I want Safari to occupy the right half of the screen. However, it occupies the left half of the screen. How to solve this problem? Thank you!

**Comment by rxhanson** [comment]
Is your window movement animated, as in, you can actually watch it move when you perform an action? If so, then this is a macOS bug (see https://github.com/rxhanson/Rectangle#window-movingresizing-appears-animatedsmooth-instead-of-quick-and-windows-dont-end-up-where-you-expect)

**Comment by aslibdnw** [comment]
Yes, my window movement is animated.

**Comment by rxhanson** [comment]
Unfortunately, there's nothing I can really do about it. As mentioned in the Readme, it's possible you can avoid it by not using the on screen keyboard, removing unnecessary apps from the Accessibility privileges in System prefs, or not using certain apps like Dragon or Punto Switcher. Otherwise, all I can do is recommend that you file a bug with Apple.

**Comment by aslibdnw** [comment]
OK. Thanks!
