### ISSUE TITLE
Part of the maximized window is displayed behind the Dock on macOS Sequoia

### ISSUE THREAD

**Issue by ilya-kozyr** [rxhanson/Rectangle#1477]
After updating to macOS Sequoia when window is maximized using the "Maximize" action it enlarges for the entire screen, the part of the window in displayed behind the Dock.

<img width="1440" alt="Screenshot 2024-09-24 at 09 03 38" src="https://github.com/user-attachments/assets/206463a3-4df4-4de3-a704-6bf65f161781">

[Screen Recording 2024-09-24 at 09.03.04.webm](https://github.com/user-attachments/assets/d1bfc151-2144-4c49-84ce-e95b72e86127)

On the previous macOS versions the Dock area was "ignored" and the window border was touching the Dock border.

macOS version: 15.0
Rectangle version: 0.83 (89)

**Comment by rxhanson** [comment]
Thanks for the detailed report. Unfortunately, this bug is on the macOS side as Rectangle is getting the usable size of the display from macOS. It typically happens when a display is connected or disconnected and the Accessibility API appears to not be updated with the proper dock information. I don't think this is a regression associated with Sequoia since it was an issue before. Some workarounds were executing the shortcut twice or hiding & showing the dock.

**Comment by ilya-kozyr** [comment]
>this bug is on the macOS side

As I thought and what I was afraid of.

The only thing I disagree is that this is not associated with Sequoia: on Sequoia Dock is broken really bad (can't be displayed on external displays as easy as before). The workaround with hiding/showing Dock didn't helped me.

So, hope Apple will be able to fix the Dock and Accessibility API issues and don't spent a century for it :)

**Comment by ilya-kozyr** [comment]
Issues are fixed in macOS 15.1 from Apple side.
