### ISSUE TITLE
Get to Preferences when icon is hidden

### ISSUE THREAD

**Issue by Toontje** [rxhanson/Rectangle#151]
macOS version: 10.15.4
Rectangle version: Latest today (i don't know which version because i cannot get to the Preferences)

Find a way to get to the Preferences when menu icon is hidden. You have to revoke Accessibility permissions and relaunch to get to the Preferences. Launching the app from Finder as mentioned in the Preferences pane doesn't work.

**Comment by rxhanson** [comment]
Thanks for reporting. I've checked in a fix for it, but am waiting on another item or two before I push out another release.

**Comment by rxhanson** [comment]
v0.28 includes the change that should fix this:
https://github.com/rxhanson/Rectangle/releases/tag/v0.28

**Comment by jgopel** [comment]
I'm seeing this (or something similar to it) in version 0.30.

macOS version: 10.15.4
Rectangle version: 0.30

More detailed steps for the workaround mentioned in the OP, since it took me a bit to figure it out: 
1. In System Preferences->Privacy->Accessibility, select rectangle and remove it by pressing the minus button. Unchecking it did not work for me.
2. Ensure rectangle is not running (I sent SIGTERM via `htop`, but I'm sure activity monitor would work as well).
3. Relaunch Rectangle. You will be prompted to enable the accessibility setting, follow the prompts and enable it. This should open the preferences.
4. Now that you're in the preferences, if you need to get back without doing these steps over, disable the "Hide menu bar icon" option.

**Comment by rxhanson** [comment]
Hmmm. I think I'll change it so it just opens the prefs window instead of the menu from the menu bar. Apple's change some stuff in this last version of macOS.

Until then, this is an easier way to get it back.

`osascript -e 'quit app "Rectangle"'`
`defaults write ~/Library/Preferences/com.knollsoft.Rectangle hideMenubarIcon -bool false `
`open -a Rectangle`
