### ISSUE TITLE
Missing some translation and minor language issue (IT)

### ISSUE THREAD

**Issue by ildede** [rxhanson/Rectangle#157]
macOS version: 10.15.4
Rectangle version: 0.29 (34)

I've just installed Rectangle to give it a try.
I'm writing this issue because i don't have the time, right now, to fix it.

This part is left untranslated:
<img width="295" alt="Schermata 2020-05-21 alle 15 08 15" src="https://user-images.githubusercontent.com/3754465/82563146-cc0be800-9b76-11ea-8ad9-4c767ad0c57e.png">

This button has text cutoff
![Schermata 2020-05-21 alle 15 07 34](https://user-images.githubusercontent.com/3754465/82563220-ef369780-9b76-11ea-8ceb-d5d16617759d.png)

The word "shortcut" is been translated as "scorciatoia" like in the images below, but Apple use the word "abbreviazioni" in system's preferences, I think is better to keep consistency with Apple convention.
<img width="497" alt="Schermata 2020-05-21 alle 15 09 26" src="https://user-images.githubusercontent.com/3754465/82563386-489ec680-9b77-11ea-905a-35253a7252d8.png">
<img width="749" alt="Schermata 2020-05-21 alle 15 09 03" src="https://user-images.githubusercontent.com/3754465/82563379-450b3f80-9b77-11ea-90fc-3ef9779515ec.png">

**Comment by rxhanson** [comment]
Thanks for filing this!

1. Welcome window (untranslated): This was added after Rectangle was translated. If you feel inclined to contribute and would like to update the translations for this, that would be awesome. You can find the translation file here: https://github.com/rxhanson/Rectangle/blob/master/Rectangle/it.lproj/Main.strings
1. Authorize window: To me, the button seems ok. Am I missing something?
1. Gear tab: I went ahead and changed it. It'll go into the next release.
1. Shortcuts tab: This is actually from the open source library that I use, [MASShortcut](https://github.com/shpakovski/MASShortcut). It would be best to get it changed there, so that Rectangle doesn't diverge, and so that MASShortcut is consistent for everyone. I could file a PR for it, but maybe it would best come from an Italian speaker?

**Comment by ildede** [comment]
I will definetly submit a PR in the next days ;)

To let you know about "2 Authorize window", the word _apert_ doesn't mean nothing in Italian.
It looks like a truncated word, but looking at Main.strings it's just a wrong word put there.
`/* Class = "NSButtonCell"; title = "Open System Preferences"; ObjectID = "iWV-c2-BJD"; */
"iWV-c2-BJD.title" = "Apri Preferenze di sistema apert";`

I will check MASShortcut for number 4.

Thanks for your work!

**Comment by ildede** [comment]
"next days" is something that I never have to write anywhere! T_T

@rxhanson I've checked MASShortcut and fix some translations with a PR there (https://github.com/shpakovski/MASShortcut/pull/146).

**Comment by ildede** [comment]
I've submitted PR #188 for this issue.
It solves the missing translation of welcome window and the correct usage of _abbreviazione_.
I've seen from the commit that you already remove the _apart_ in the Authorize window, so... good job!


Thanks a lot for Rectangle, it's been some months of usage for me by now and I am pretty happy with that!

**Comment by ildede** [comment]
PR #188 is merged, I close this issue.

Thanks again.
