### ISSUE TITLE
Resizing two windows together – possible?

### ISSUE THREAD

**Issue by borekb** [rxhanson/Rectangle#160]
Quite often, I have side-by-side windows that I need to adjust slightly, e.g., move the "split" between them slightly to the left or to the right. Right now, I'm just adjusting the two windows separately, by dragging their edges (like you do in plain macOS).

I wonder if Rectangle could add something that would make this common operation easier – if that's even possible. For example:

- Invoking a shortcut like `ctrl-alt-cmd-[` makes the left window 20px narrower and the right window 20px wider. I'd repeat this shortcut a couple of times to create a layout I'm after.
- Invoking a shortcut like `ctrl-alt-cmd-]` moves the "split" in another direction, i.e., the makes the right window 20px narrower and the left one 20px wider.

Something like that... Just wanted to ask if it's even technically possible. Thanks.

**Comment by rxhanson** [comment]
This is technically possible, but it could add a decent amount of complexity to Rectangle. Currently Rectangle only manages the frontmost window. In order to do this, it would have to keep tabs on other windows and this is more complicated than it sounds. If you wanted to implement something in a fork, I don't mind providing more info on this. I'm not directly opposed to merging something like this into Rectangle, but it would have to be an elegant solution and either a straightforward user experience or a Terminal flag config. 

Closing since I don't have plans to implement it.

**Comment by borekb** [comment]
> In order to do this, it would have to keep tabs on other windows and this is more complicated than it sounds.

Ah that's a great point. Makes the feature probably quite difficult / fragile.

**Comment by rxhanson** [comment]
Indeed it does. Amethyst does handle resizing multiple windows dynamically, so it's definitely possible. The way Amethyst does it was really kind of jarring for me last time I tried it since it will resize all windows when you change the size of one window, but I think it would be better to have it resize only on shortcut execution as you've suggested.

**Comment by andrewjong** [comment]
Thoughts on reconsidering this feature? I really love the way Swish implements resizing windows together by dragging their shared edge. It can even drag multiple windows at once by selecting their shared corner. However, what Rectangle has that Swish lacks is keyboard shortcuts to tile, and dragging to the edge of the screen to tile. It'd be cool if Rectangle could have this same feature as Swish.
