### ISSUE TITLE
Feature request: Improved support for wider screens

### ISSUE THREAD

**Issue by seime** [rxhanson/Rectangle#161]
Currently there is support for resizing windows to use half or a third of the screen.

![image](https://user-images.githubusercontent.com/1565156/83115747-22bf7780-a0cb-11ea-9b94-6dee3c088463.png)

With newer real wide displays being available for some time now it would be very useful to resize windows to using a quarter of the screen - having 4 new window positions (1st - 4th quarter).

**Comment by rxhanson** [comment]
There's 2 limiting factors here. 
1. I don't currently have the time to add in additional window actions.
2. The UI is a little maxed out on window actions in its current form.

There's other considerations, too - like adding 3/4 sizes and center 1/2 if quarters exist. Another one is what to do with repeated executions, although that's not needed on initial implementation. 

Closing this one out due to limiting factor 1, but I'm not opposed to merging a PR if limiting factor 2 is solved elegantly.
