### ISSUE TITLE
Cascading Windows

### ISSUE THREAD

**Issue by ElvinGarcia** [rxhanson/Rectangle#168]
Is there anyway of arranging all open windows into a cascade layout?
![cascading windows](https://i.stack.imgur.com/hT9Ev.png)

**Comment by rxhanson** [comment]
Kind of, but not quite exactly what you want. The accessibility API that window managers use let you manipulate the frontmost window or windows at specific coordinates. You could cascade all of the currently visible windows at a specific point in time (i.e. the time that you execute a keyboard shortcut), so if you had a window that would be underneath the first cascaded window then it would just be hidden. Rectangle doesn't keep track of all windows - it just grabs the frontmost. You'd have to keep track of all the windows in order to know where to grab each visible window from to add it to the cascaded pile.

This isn't something I'd add into Rectangle, since it would be a significant amount of work and would have kind of odd behavior as mentioned.
