### ISSUE TITLE
Rectangle doesn't launch on login, even though option is checked in preferences

### ISSUE THREAD

**Issue by adamxtokyo** [rxhanson/Rectangle#17]
Hey,

So I've noticed I always have to start Rectangle manually after system restarts, even though I've checked the launch at login option in the preference panel.

Maybe it's my system, but I thought I'd report it so that you can investigate further.

I'm using:
macOS 10.15 (19A583)
Rectangle 0.7 (9)

![Screenshot 2019-10-09 at 10 51 45](https://user-images.githubusercontent.com/13076573/66471201-3611ca00-ea8b-11e9-808d-eb72b3b2ea13.png)

**Comment by rxhanson** [comment]
Launch on login is working fine for me with macOS 10.15 and Rectangle 0.7, but it could be working because of all of the development versions of Rectangle that are registered on my machine from working on it.

Has this ever worked for you, or did it break with an update?

Apple had deprecated old ways of doing launch on login, so Rectangle uses the same launch on login behavior that is recommended for sandboxed apps - the service management framework. If you don't mind, could you check and see if the RectangleLauncher is registered to launch when you check the box? To do this, the best way I know is to use this guy's program: https://github.com/keith/SMLoginItems/releases

If you change the setting in Rectangle, you'll have to hit the refresh button on the SMLoginItems app to see the change. 

I'll do some more testing and see if I can reproduce it as well.

**Comment by adamxtokyo** [comment]
Thanks for your swift reply @rxhanson!

I downloaded the SMLoginItems app, and looked for Rectangle in the list but couldn't find it... I then disabled and re-enabled launch on login and refreshed the SMLoginItems app and there it was. Restarted my mac just to make sure it was working and yes - it does work now!

I updated my OS last night, so that might have been what triggered the bug? Not sure, but as I can't find a way to reproduce it (and I'm guessing you can't either), I think we can consider this issue closed for now.

PS. Thanks for making and maintaining this awesome app 🙏😌

**Comment by marlonrichert** [comment]
@rxhanson I recently updated to macOS Catalina and since then, Rectangle no longer launched at login for me either, even though the preference was still checked. I now toggled the preference and that fixed the issue for me, too. So yes, this does seem to be related to updating to macOS 10.15.

Thanks for the tip, @adamxtokyo.

**Comment by rxhanson** [comment]
@marlonrichert thanks for posting your experience on this. It's one of those issues that I thought about for a while if it's worth the time and added complexity to put a fix in the code. Right now my plan is just to leave it out and let people look here for the workaround.

**Comment by dylan-chong** [comment]
"launch on login" hasn't been working for me either on 10.14.6 (mojave).

I'll just stick with dragging the app into "Login Items" under "Users and Groups" System Preferences for now

**Comment by rxhanson** [comment]
@dylan-chong, did you try the mentioned SMLoginsApp (https://github.com/keith/SMLoginItems/releases) to see if Rectangle was being properly registered (or deregistered) with macOS when toggling that checkbox?

**Comment by dylan-chong** [comment]
RectangleLauncher appears to be listed in that app

**Comment by chrismillerkeys** [comment]
I have this issue as well. Rectangle was installed via Homebrew on Ventura 13.6 (M2 Max Mac Studio), and it doesn't matter whether I drag-n-drop the app into Login items, click the app's checkbox to Launch at Startup (also unchecked and rechecked), or click the [+] button in Startup Items. When installed via Homebrew, the app does not register as a startup item, as confirmed by the SMLoginItems tool.
