### ISSUE TITLE
4-key shortcuts can't be assigned

### ISSUE THREAD

**Issue by reed-jones** [rxhanson/Rectangle#173]
macOS version: 10.14.6
Rectangle version: 0.30 (35)

I have my Caps Lock key setup as a 'hyper' key by mapping it to Shift+Control+Option. In spectacle it was essentially used as my 'window movement' key so Caps+left is left half of screen, etc. Unfortunately it seems Rectangle doesn't listen beyond 3+ keys for shortcuts (so Shift+Control+Option+C for 'center' (Caps+C) won't work.

Not sure if this would be a better issue over at [shpakovski/MASShortcut](https://github.com/shpakovski/MASShortcut)

**Comment by rxhanson** [comment]
This is an issue with MASShortcut, but I don't really know what's going on with it. Shift+Control+Option+C is recordable for me, as are other 'hyper' shortcuts. You can try other hyper shortcuts and maybe provide more detail about what works for you to MASShortcut. I've spent a decent amount of time in MASShortcut's code and I'm kinda stumped by it. Other users have reported similar issues, and I've spent some time thinking it through but I can't determine a pattern from it. If you don't mind filing an issue with MASShortcut, that would be great. I haven't done so since I can't personally reproduce it.

**Comment by reed-jones** [comment]
OOOOOhhhhhhhh. you know what. I am a goof. I have it bound in spectacle and had spectacle open so I could reference my previous keybindings. Instead of binding my shortcut, I was just centering the Rectangle preferences panel (which was already centered. 🤦 . Just unbound in spectacle, and of course it works as expected.

I shouldn't be opening Issues before my morning coffee it seems...

**Comment by rxhanson** [comment]
Thanks for the update. Well, if you do happen to come across the issue I've mentioned, definitely post back! I've gone down this path with a couple other users and been unable to find a conflicting keybind.
