### ISSUE TITLE
Sixths window snapping

### ISSUE THREAD

**Issue by Dr2n** [rxhanson/Rectangle#177]
Would Rectangle be open to adding the option of snapping to sixths of the screen space (e.g. half of thirds)? This would be excellent for larger 4K or higher resolution screens where each window would still be at a comfortable size.

I would be willing to write a fork/pull request to add this feature.

**Comment by rxhanson** [comment]
It's definitely apparent that Rectangle needs more options for large displays. Sixths is probably the most intuitive one to add next.

One of the main things standing in the way of this is unfortunately the UI - both the menu in the menu bar and the prefs window are kind of at a threshold (or maybe past a threshold) for how full they are.

Here's some options for the prefs window:

- Add a new tab in the prefs window for the new actions, and maybe even move some of the current window actions over to the new tab. I tried this out a long time ago and didn't like it too much from a user perspective.
- Add an expandable area to current shortcuts tab that contains the new shortcuts, and maybe some of the old ones could go in it, too. I like this idea better but it's a little more effort than the additional tab. 

Ideally a user could configure which items show up in the menu bar menu, but that's a decent amount of work to get configuration set. We could add all of them in to start and have a terminal command to tailor the list.

**Comment by sstarcher** [comment]
I came here to create this exact feature request.  For a first round of customization could it be done with just a configuration file and no UI element if that makes it faster?  I also run a ultrawide.  I run it in thirds with the middle split into sixths.

Currently I place some windows in the first third and some windows in the last third.  For the middle I drag them to the third and I shrink them either into the top 6th or the bottom 6th.  Being able to customise this and have the middle selectively snap to 6ths would be fantastic.

**Comment by rxhanson** [comment]
@sstarcher Normally I would look to add in something like this as a terminal command config. For keyboard shortcuts, it's oddly easier to just implement the UI instead of building something else to handle config parsing. For drag to snap areas, this is something that a Terminal command config would be fairly quick and easy to implement. At the moment, I don't have the bandwidth for either but would be open to a PR.

**Comment by brianczapiga** [comment]
On an ultrawide display, I'd prefer 4th (8ths) actually. Right now I'm running two 25" displays side by side, and usually use the ^-option-left and ^-option-right short cuts to divide my workspace in one half of one display. When I upgrade to the ultrawide, I'll be looking for similar functionality, although I can just run two HDMIs into the display and use it as if it were two monitors.

**Comment by rxhanson** [comment]
@brianczapiga As long as there's an elegant way to tuck away extra window actions, whether it be 6ths or 8ths or anything, I would most likely be inclined to merge a PR for any window actions anyone would like to add in. 

With that said, this starts to feel like https://github.com/rxhanson/Rectangle/issues/7. Instead of having a ton more keyboard shortcut recorders, it would probably be better to have a UI built into Rectangle that allows custom grids like some other window managers have. Rectangle could have a scripting engine API, but hammerspoon already solves that.

**Comment by Dr2n** [comment]
Sorry for the late response to this. Looks like there is demand for doing a sixths or eigths feature :) . I hadn't anticipated that the UI would be the main blocker to this. I'd also initially thought that this would only involve the changing of a few values, but have some time in the coming weeks and would still be happy to make an attempt at a PR.

> - Add an expandable area to current shortcuts tab that contains the new shortcuts, and maybe some of the old ones could go in it, too. I like this idea better but it's a little more effort than the additional tab.

@rxhanson Do you have any concrete examples on how you'd like an expandable area to look? e.g. other apps that have a similar area. I think it'd make sense to put the current thirds options into this new area as well. I'd really like to preserve the cleanliness and simplicity that you have in the UI at the moment.

**Comment by rxhanson** [comment]
@Dr2n Here's an example project from Apple to take a look at:
https://developer.apple.com/documentation/appkit/views_and_controls/organize_your_user_interface_with_a_stack_view
Using stack views in this way is probably the best way to do it in my opinion. I expect that getting it all set up right with autolayout will be the most annoying part of this task.

Putting the current thirds in this area sounds good to me. Let me know if you hit any bumps.

**Comment by rxhanson** [comment]
Just a heads up that I added the "expandable area" for shortcuts in v0.32. I'm up for merging in any PRs that add additional window actions.

**Comment by rxhanson** [comment]
I'm planning on adding this in for the next release (in case anyone was considering working on it, now you don't have to :)

**Comment by Dr2n** [comment]
So sorry, never got round to actually doing this. Thanks so much for your amazing work, really looking forward to seeing sixths snapping! :)

**Comment by rxhanson** [comment]
If anyone can test out the beta for this, that would be awesome:
https://github.com/rxhanson/Rectangle/releases/tag/0.33

**Comment by Dr2n** [comment]
Just installed, seems to be working great! 👍 

The only issue that I've picked up is that gapSize set through `defaults write com.knollsoft.Rectangle gapSize -float <NUM_PIXELS>` isn't being picked up.

**Comment by rxhanson** [comment]
I was going to add a slider in for that in the actual release. In the meantime, make sure that you restart the app after setting that. If it still doesn't work then try adding .plist, eg: `defaults write com.knollsoft.Rectangle.plist gapSize -float 10`

**Comment by johnpg** [comment]
The beta is working great for me. I have an ultrawide display and it's great having sixths. I remapped Ctrl Option U, I and O and J, K and L to those and it's working perfectly. Thank you for your amazing work! I also love the toggling feature where you can hit Ctrl Option U over and over and it cycles through the positions (same for Ctrl Opt D). I don't know if that's new or not, but it's nice. 

It makes me wish for a way to use Ctrl Opt + arrow keys to switch between sizes and cycle. The default behavior is to cycle between full height options with left/right and full length with up/down. What I want is up/down grows/shrinks height (full or half) and then left/right grows or shrinks the widths (1/4 1/3 1/2, etc), but retains the height you set and vice versa. I hope that makes sense. This app is so versatile I wouldn't be surprised if it already does this and I just haven't found it yet.

**Comment by rxhanson** [comment]
@johnpg Thanks for trying out the beta and for the feedback. I like your idea, but I think it might be a little beyond the scope of Rectangle.

There is a way that you can build that idea, or something close to it in my paid app, [Hookshot](https://hookshot.app) (No pressure if you're not up for trying it out). I recently added the "Make your own shortcut" tab (the wrench/ruler icon). In this tab, you can basically build out any desired window sizes and locations that you want to apply to a keyboard shortcut and it's repeated executions. The UI is a tad cumbersome, since it's my first cut at the feature, but it provides a great deal of customization. Originally I started writing this feature for Rectangle but felt that it was too complicated for it. Also, I'll be adding the contents of this Rectangle release to Hookshot once this release is out of beta.

**Comment by johnpg** [comment]
Thanks @rxhanson I tried Hookshot and I think the custom idea is really great. I wasn't able to get it to do what I wanted though, but that might just be my mistake. I'll play around a bit more and see if I can figure it out.

**Comment by rxhanson** [comment]
@johnpg Thanks for trying it out! I'm going to write a blog post on the details of it soon.

**Comment by Dr2n** [comment]
@rxhanson Just had a try with the .plist command, and also restarting Rectangle afterwards, but still no luck with gaps on sixths. Gaps for the other snap sizes seem to be adjusting as intended.

I also noticed that VSCode will sometimes refuse to snap until quit and restarted. There will be no response to keyboard shortcuts, and no 'snap size preview' when dragging the window to the edges of the screen. I'm not sure if any changes in this beta might lead to this so perhaps this is just something related to my own environment.

**Comment by rxhanson** [comment]
@Dr2n Sorry about that! I just realized that although I set those actions up to be ready for gaps, I never actually connected them to the gap logic. Thanks for your patience. I'm looking to publish a release soon, just a couple more things left.

**Comment by rxhanson** [comment]
This is now out of beta in [v0.34](https://github.com/rxhanson/Rectangle/releases/tag/v0.34). Please open a new issue if there are any problems with it.

**Comment by rxhanson** [comment]
@Dr2n Sorry didn't notice your other comment about VSCode until now. This is not something that Rectangle has any control over, and has been reported in a couple other issues. Might be a bug with VSCode specifically, might be a bug with Electron, so I'm not sure exactly where the right place to file a bug would be.

**Comment by quinncomendant** [comment]
I just updated to v0.35 and was excited to try the sixths functionality. I'm a bit confused. I was expecting the sixths feature to allow window sizes to cycle through these sizes, for each of the `Left`, `Center`, and `Right` positions:

    1/6 → 2/6 → 3/6 → 4/6 → 5/6 → 1/6 → …

Currently I'm using `Left Half` and `Right Half` to cycle through its various sizes on the left or right side of my screen. But, it doesn't really go narrow enough on my ultrawide screen; that's why I was cheering this sixths functionality.

Did I misinterpret how the sixths are suppose to work? I do see that there are `{Top,Bottom} {Left,Center,Right} Sixth` options now, which is also a welcome addition.

Thanks for your time, @rxhanson!

**Comment by rxhanson** [comment]
@quinncomendant I have received a lot of requests for a 3x2 grid of sixths, and not really any requests for a 6x1 grid. This is why I interpreted this request as a 3x2 grid. 
> (e.g. half of thirds)

At this point, Rectangle is kind of maxed out in terms of shortcuts that I am looking to add into it, but I'll think a little more about adding just two shortcuts for cycling 6x1 grid forward/backward. Either way, I'll plan to add these to Hookshot (in which you could already configure exactly these in the "make your own shortcut" section that currently exists), but I can see adding just these two to Rectangle and then calling Rectangle's list complete. It does seem weird to me to just have a first & last shortcut that implies that the user must repeatedly press them to get the rest of the sixths, but it's probably less of an issue than I'm thinking. I'll post back when I decide what I want to do.

**Comment by rmebjesus** [comment]
> @quinncomendant I have received a lot of requests for a 3x2 grid of sixths, and not really any requests for a 6x1 grid. This is why I interpreted this request as a 3x2 grid.
> 
> > (e.g. half of thirds)
> 
> At this point, Rectangle is kind of maxed out in terms of shortcuts that I am looking to add into it, but I'll think a little more about adding just two shortcuts for cycling 6x1 grid forward/backward. Either way, I'll plan to add these to Hookshot (in which you could already configure exactly these in the "make your own shortcut" section that currently exists), but I can see adding just these two to Rectangle and then calling Rectangle's list complete. It does seem weird to me to just have a first & last shortcut that implies that the user must repeatedly press them to get the rest of the sixths, but it's probably less of an issue than I'm thinking. I'll post back when I decide what I want to do.

Actually I actually also thought that the sixths would be 6x1 and was surprised by the 3x2. For ultra wide screen users (49” 32:9 here) 6x1 is more useful as we are more bounded by vertical resolution and have horizontal one to spare.
But it great to know that you’ll add it 🙂, many thanks for that!

**Comment by brianczapiga** [comment]
Just throwing my comment in, I have a 41" 32:9 and I expected 3x2 not 6x1, so this is good. I think I would need at least a 49" for 6x1.

**Comment by johnpg** [comment]
I like the 3x2 and it's working great for me, but I can see the utility of 6x1. I too have an ultrawide display. Having said that, maybe the way to go on this is to make it configurable? Not to the point of Hookshot, but maybe allow people to choose from the various sizes and assign those to any hotkey they want. Out of the box it works the way it does now, but someone could change it as needed. 

Right now there is a list of sizes/placements and a corresponding hotkey. Why not instead allow users to create as many hotkeys as they want, and then choose between any size/placement for that hotkey, with the ability to group them for cycling? Having said this, I'm aware that's probably a massive change, but it would solve this issue. And if you had Hookshot's ability to add your own size/placement then people could handle their own special case situations. I still think it's important to have a sensible out-of-the-box experience so people don't have to do any of this unless they want/need to. 

Just a thought.

John

**Comment by rxhanson** [comment]
@rmebjesus Just to be clear, I'm not committing to adding 6x1 grid into Rectangle, although I'm not saying I won't do it.

@johnpg I have no plans to add further degree of customization to Rectangle. If someone want's a more customizable tool then Hookshot _is_ the only solution I plan on supporting.

**Comment by johnpg** [comment]
@rxhanson Yup, makes sense. I don't know if you like my idea or not, but if you do I'd love to see it in Hookshot.

**Comment by rxhanson** [comment]
@johnpg If I understand correctly, I think Hookshot does encompass your idea (although I won't fault you if you've tried out Hookshot and didn't catch exactly how it works - the UI is still a WIP). 

> Right now there is a list of sizes/placements and a corresponding hotkey. Why not instead allow users to create as many hotkeys as they want, and then choose between any size/placement for that hotkey, with the ability to group them for cycling?

<img width="567" alt="Screen Shot 2020-10-10 at 10 40 39 PM" src="https://user-images.githubusercontent.com/13651296/95664643-1dc70600-0b4a-11eb-8235-022f61f085b6.png">

This custom configuration has one keyboard shortcut for cycling through all of the sixths of a 6x1 grid. You can add as many shortcuts as you want, and as many cycling nth executions that you want. Obviously, that's more work to build that than it is to just have a preset keyboard shortcut, but to me it's not an absurd amount of work, either considering how often most users will configure their keyboard shortcuts. At the very least, I do plan to add "stock" 6x1 grid sixths to Hookshot in its list of built-in shortcuts, some way or another.

Let me know if I misunderstood what you're looking for there. There are definitely areas of improvement on this functionality in Hookshot, and I am open to suggestions. 

As mentioned earlier in the thread, I originally built that functionality for Rectangle but prefer keeping it a "does-one-thing-well" tool where you just have one non-scrolling screen that shows all of your shortcuts. And, in order to keep it that way, you gotta draw the line somewhere with what features and shortcuts get added in.

**Comment by johnpg** [comment]
Thanks @rxhanson 

Yes, that's basically what I'm talking about. The only difference is Hookshot doesn't include all of the various options in the dropdown. For instance in the version I have I see the below options.

![image](https://user-images.githubusercontent.com/6257/95665580-9e641300-0b06-11eb-921a-aaf7e52cfd20.png)

But the built-in options have a lot more. Of course, if they are in the list of built-ins maybe there's not really a need to customize them. But that's what I expected to see, at least. I'm not sure if others agree or not. 

![image](https://user-images.githubusercontent.com/6257/95665607-e5ea9f00-0b06-11eb-8910-15964a3ef56e.png)

John

**Comment by rxhanson** [comment]
@johnpg I think there's a misunderstanding here due to the currently poor UI in the custom shortcut builder. 

The short list of options in the builder contains "docking points" for your window, not window actions. You can construct any of the long list of actions using a "docking point" plus size/location parameters (except for fill left/right and across displays actions). For example: center third would be "Center, W: 1/3, H: 1"

I'll be updating the UI of Hookshot to make this more clear in the future, and will consider adding a dropdown to just pick an existing action instead. (I have been also meaning to write a detailed post on how the custom builder works, but maybe I'll just wait until I rework the UI. Thanks for the feedback!)

At any rate, this is starting to deviate pretty far from a sixths window snapping discussion. I'm fine with a separate issue being opened or even just an email if anyone wants to discuss further. 

**In terms of a 6x1 grid on Rectangle**: I'm not going to make any sudden movements there. I'm going to let the current version roll for a while and see how I feel about it. If anyone feels more strongly about it in the near term, then feel free to open a PR.
