### ISSUE TITLE
Preconfigured layouts

### ISSUE THREAD

**Issue by chitalian** [rxhanson/Rectangle#180]
This feature might be too heavy for rectangle, so it may be best to have it live in a separate repo. The idea is to have a preconfigured layout that can be easily set with a key combination. 

Ex: 2 x 2
```
|-------------------|-----------------|
|   Browser         |     Iterm       |
|-------------------|-----------------|
|     Finder        |     Discord     |
|-------------------|-----------------|
```

**Comment by chitalian** [comment]
close because it was discussed here: https://github.com/rxhanson/Rectangle/issues/7

**Comment by rxhanson** [comment]
Right, I would've suggested hammerspoon (https://www.hammerspoon.org/go/#winlayout) for this as well. Thanks for checking through previous issues!

**Comment by chitalian** [comment]
Yeah that's exactly what i was looking for! Thanks :D

**Comment by chitalian** [comment]
@rxhanson I do still kind of like the idea of forking Rectangle (Plus I want to learn more swift too) and adding these features so that less tech savy people would be able to set it up quickly. What do you think?

**Comment by rxhanson** [comment]
Go for it! It's a more challenging first issue from my perspective, but sometimes that's better for learning. It's also one of those issues that is kinda hard to strap a UI to (maybe a way to record current window layout to configure it). Honestly, I'm not sure how hammerspoon does it as I haven't looked through their code, but this would be something valuable to Rectangle for other requested features as well. In order to do it, you'd probably have to keep track of all of the windows as they're opened and closed, as opposed to Rectangle where it just looks at frontmost or window under cursor. I'd be interested to hear what you find if you make progress on it.
