### ISSUE TITLE
Import/Export JSON file for hotkeys to promote sharing

### ISSUE THREAD

**Issue by Karric** [rxhanson/Rectangle#190]
One thing I liked about Spectacle was that the hotkey mapping file was just a json file in Application Support. This made it easy to give other people a specific hotkey mapping.

Would be helpful if Rectangle could match this, possibly with a more explicit import/export option instead.

**Comment by rxhanson** [comment]
There is a previous conversation about this in issue https://github.com/rxhanson/Rectangle/issues/25

As noted in that issue, I have no plans to add this in myself. But, I can understand that sharing your config would be simpler via JSON and accessible in the UI as opposed to hunting down the plist. If anyone wants to implement this, I don't see any reason to turn down a good PR.

**Comment by ladislas** [comment]
Not sure if related, but having iCloud sync the settings would be also a nice add on.

**Comment by rxhanson** [comment]
Import/Export JSON file is actually in, but I was experiencing some really laggy behavior with the Open/save panel in macOS so I left the buttons hidden by default until I could figure out if it was just something that I was experiencing because of my dev setup or if it has to do with the fact that Rectangle is not (and cannot) be sandboxed. 

If anyone is up for testing it out, you can execute the following terminal command and restart the app to get the import/export buttons in the settings tab of the prefs window:

`defaults write com.knollsoft.Rectangle showExportImport -bool true`

I have no plans to add iCloud sync in for Rectangle (sorry!), mainly because handling iCloud sync with the shortcut recorder (MASShortcut) requires some nontrivial changes for preventing cloud storage echoing pitfalls. I did add iCloud sync into my paid superset of Rectangle, Hookshot (https://hookshot.app).

**Comment by gibfahn** [comment]
Tried the import/export and it works really well!

Only thing that would make it better for me would be a programmatic way to save/load, so my new machine setup scripts could automatically make Rectangle load the config instead of having to do it manually every time.

If the answer is "you should use hookshot instead" then that's fair 😁 .

**Comment by rxhanson** [comment]
@gibfahn Thanks for testing it out and reporting back! I will probably have these shown by default in the next release.

I don't think I'll add in the programmatic save/load, but I wouldn't be opposed to merging a PR with that functionality.

**Comment by rxhanson** [comment]
Closing this since the settings buttons are now shown in v0.44.
