### ISSUE TITLE
'Check for updates automatically' is broken

### ISSUE THREAD

**Issue by ahydronous** [rxhanson/Rectangle#194]
macOS version: 10.15.5 (19F101) (Catalina)
Rectangle version: 0.30 (happened in older versions too)

As the title says, 'check for updates automatically' is currently broken and has been for a while. Almost every time I decide to hit the 'check for updates' button (so about once every month or so) it'll notify me there is a new update to download, even when the update is weeks old and should have been automatically detected.

**Comment by rxhanson** [comment]
Thanks for reporting. If you don't mind, could you run the following terminal command and let me know what the result is? 

`defaults read com.knollsoft.Rectangle.plist`

I only really care about the fields starting with SU since that's the Sparkle updater library values.

It behaves properly for me, so I'm wondering what could be different about your setup. Checks are supposed to happen about every two days.

**Comment by ahydronous** [comment]
```
SUEnableAutomaticChecks = 1;
SUHasLaunchedBefore = 1;
SULastCheckTime = "2020-07-16 01:58:50 +0000";
SUUpdateGroupIdentifier = 1558868086;
SUUpdateRelaunchingMarker = 0;
```

**Comment by rxhanson** [comment]
All of this looks good, so there could be an edge case in Sparkle that's not working properly. Rectangle's Sparkle version is behind, so I'm going to first update to the latest Sparkle version and will dig deeper if the problem persists.

**Comment by rxhanson** [comment]
Just checking in on this one - let me know if you do or don't get an automatic update for v0.34 within the next couple of days (or if anyone else experiences this issue with v0.34).

**Comment by rxhanson** [comment]
This continues to work properly for me, so I'm going to just close this out as part of housekeeping. Let me know if you still have issues.

**Comment by ahydronous** [comment]
This problem still persists, and I know for sure that it is a Rectangle-specific problem as Viscosity (that also uses Sparkle) perfectly notified me with a pop-up that an update was available.

**Comment by rxhanson** [comment]
Since I can't reproduce this, is there anything that might be unusual about your Rectangle installation, or Rectangle's ability to connect to the network. Perhaps installed via brew with any unusual brew settings, or having little snitch or something like that blocking it? This seems unlikely to me especially since SULastCheckTime is a valid date, but just trying to rule things out.

I believe the way Sparkle works is that the check only happens when Rectangle becomes frontmost - which is often only when you open the Rectangle window. I know that you reported that you had to press the Check for updates button, though.

Perhaps you can try setting `SUAutomaticallyUpdate` to YES (true) in Rectangle's Info.plist (show package contents on the app in Finder). Then we can see if it will just automatically install updates (without the prompt).

It's also possible to trick the app to auto-check when you want, but I don't think that would really get us anywhere. 

There's nothing unusual about Rectangle's sparkle usage. This is pretty puzzling since it works for me, no other users have reported this, and there are a lot of update requests going to the server that look to me to be the automatic ones - which points to expected behavior.

**Comment by ahydronous** [comment]
Yeah I know you can't help it either, I thought I'd just keep you updated about it. Might do a clean install on Big Sur so fingers crossed that might fix it.
