### ISSUE TITLE
Big Sur Safari Bug

### ISSUE THREAD

**Issue by akumar2021** [rxhanson/Rectangle#200]
macOS version: 11.0
Rectangle version: 0.31
Logs:  Unable to retrieve logs

Steps:
1. Make Safari a random size windows
2. Do any keybind for Rectangle and it fails to work properly. For example, doing cmd + option + F tries to do maximize but takes 2 presses to do so. Other key binds like cmd + option + left or right arrow don't seem to move the window to the right corner of the screen.
3. Trying using any other app. Rectangle worked perfectly fine with other apps such as Spark and Chrome for me.

Trying this with dragging to the edges of a screen instead of using keyboard shortcuts results in the same problems

I have attached a screen recording below where I try out Rectangle both on Safari and on Google Chrome, along with which buttons I am pressing while I execute a command to Rectangle. Video here: https://vimeo.com/445678950

Hope this helps! Thank you so much for making Rectangle, its been an excellent app over the couple of years I have used it.

**Comment by rxhanson** [comment]
Thanks for reporting. I'm planning on giving Big Sur a go this weekend (I typically drag my feet because I've wasted a lot of time on buggy macOS betas breaking my stuff then Apple fixing things later). 

As for this bug, well, it's a pretty common one even before Big Sur, and it's a macOS bug that unfortunately I can't do anything about. See https://github.com/rxhanson/Rectangle/issues/165

Maybe enough users will have this issue in Big Sur and report it to Apple so that they put in a fix for it.

**Comment by akumar2021** [comment]
Thanks! It's unfortunate that it has been a problem for a long time. Weirdly enough though, it's working perfectly fine today! Not sure what caused it to act up yesterday though; if I find out, I'll post it here in case that fixes issues that other people have been having as well.
