### ISSUE TITLE
Does not start during reboot or startup

### ISSUE THREAD

**Issue by francislata** [rxhanson/Rectangle#205]
macOS version: Catalina 10.15.6
Rectangle version: 0.31 (36)
logs (In Rectangle menu, hold option, "View Logging..."): N/A

I am aware that there are options within System Preferences or through the Rectangle app itself to let it start during reboot or startup. However, there doesn't seem to be any effect. I looked at previous issues related to this and no luck with those.

Is this still an active issue?

Lastly, I installed this through `brew cask ...`.

**Comment by rxhanson** [comment]
Actually, this is still an active issue. Thanks for posting. I cannot reproduce it, and it appears to only affect a small percentage of users. I will need to add some more logging to the app to narrow down precisely what is going on, which will go into the next release. 

In the meantime, there are two things you can do that would help narrow it down before I add logging.

- With the checkbox checked, try rebooting to reproduce the error scenario. Look in the Activity Monitor to see if the RectangleLauncher app is running.
- With the checkbox checked, open this app and see if the RectangleLauncher is listed: https://github.com/keith/SMLoginItems

It's ok if you don't do either of these, it would just accelerate my process of figuring out where the problem is.

**Comment by francislata** [comment]
@rxhanson Just an update, my issue is already fixed. My `brew` setup was a bit different. Initially, Homebrew was installed in my administrative account (also where Rectangle is installed). However, I'm using it on a standard account. So I believe it is with the user account privileges that prevents Rectangle from starting.

As a result, I'll closing this issue.

**Comment by rxhanson** [comment]
Good to know. Thanks for the follow up on the issue!
