### ISSUE TITLE
Unable to use L key with three modifiers

### ISSUE THREAD

**Issue by kyleboe** [rxhanson/Rectangle#230]
macOS version: 10.15.6 (19G2021)
Rectangle version: 0.32 (37)
logs (In Rectangle menu, hold option, "View Logging..."): N/A

This seems to be something super edge case. I am using ^⌥⌘ as a prefix of sorts for Rectangle (see config below). For some reason, I cannot get the L key to work with these three modifiers. I am attempting to set Right Half to ^⌥⌘L but it just won't let me.

![image](https://user-images.githubusercontent.com/4054771/94457104-fd21a800-0168-11eb-921b-e33ee43b7b8e.png)

The odd thing is using the shift variant (^⇧⌘L) as my Move Right shortcut works just fine.

Debugging steps I've taken:
- I went through my existing shortcuts to make sure there were no other collisions.
- I recently uninstalled Spectacle and double checked to make sure everything was off/removed from my system.
- [Rebooted](https://www.cipher-it.co.uk/wp-content/uploads/2017/11/ITCrow.jpg)

Any help is appreciated. Thanks!

**Comment by rxhanson** [comment]
Thanks for reporting and providing your debug steps. I've had a couple other users report a similar issue before and I haven't been able to reproduce it myself so I haven't been able to get to the bottom of it. Unfortunately, the shortcut recorder, MASShortcut, is a 3rd party library that is not easy for me to fill up with debug statements to see what's going on either.

This might sound crazy, but you could try powering down entirely, then turning back on instead of just a reboot. I've had other oddities like this solved that way before 🤦‍♂️

**Comment by theutz** [comment]
I am having the same issue with a new MBP, and powering down has not fixed the issue for me. ☹️  I love this app, though!

**Comment by rxhanson** [comment]
I'm pretty certain that this is either a MASShortcut issue or a macOS issue dealing with shortcuts binding or old shortcuts not unbinding properly. 

If I were able to reproduce it, I would hit some breakpoints in the MASShortcut code to see if I could figure out what's going on. Since I'm not able to reproduce it, adding debug to MASShortcut in Rectangle would be a lot of back and forth with someone that can reproduce it to narrow down what's going on. If anyone that has this issue can dig into MASShortcut, that would be immensely helpful.

It might be worth it for someone who has this issue to first try out the demo on MASShortcut just to verify that the issue is reproducible outside of Rectangle. (https://github.com/shpakovski/MASShortcut). Then perhaps next steps could be asking for some assistance there as well.

**Comment by ViciousCupcake** [comment]
Just an idea, could this be because of a keyboard limitation? Lots of keyboards can't detect specific keys pressed together at the same time. (see multi-key rollover / NKRO)

If so, you might get success by trying a different keyboard.

**Comment by kyleboe** [comment]
I figured it out! The prefix I was using is also (already) in use by 1Password by default. 

![image](https://user-images.githubusercontent.com/4054771/101395142-62d39400-387e-11eb-97e6-d968445e81e7.png)
Image From [1Password Support Docs](https://support.1password.com/keyboard-shortcuts/)

I changed the setting in 1Password and everything now works as expected. Thanks to all who responded!

**Comment by rxhanson** [comment]
Hooray, thanks for posting! I think this is actually what the scenario is for all of the users that I've noticed this on. It's a thing where Spectacle didn't care about the binding being taken elsewhere, and macOS doesn't give MASShortcut enough to go on as to which app has already taken a binding.
