### ISSUE TITLE
Rectangle causes some apps to lag/freeze

### ISSUE THREAD

**Issue by tmaneri** [rxhanson/Rectangle#231]
macOS version: 10.15.5
Rectangle version: 0.32

I've noticed that if I have Rectangle running and I'm using **thinkorswim.app** (TD Ameritrade's stock app) often times **thinkorswim** will freeze/lag out/beachball. I've tried checking "Ignore" in Rectangle for it, and it does seem to prevent hotkeys from functioning, but it still freezes and I can reproduce it anytime. I end up having to just close  Rectangle when I want to use thinkorswim Any ideas?

**Comment by rxhanson** [comment]
I think this might just be a thinkorswim.app specific issue, or something about it's ui (looks like a Java UI?). It appears to have trouble with another app listening to clicks on the event stream, which is done by Rectangle to get window information when snapping windows when dragging. Try disabling snap windows by dragging in Rectangle. That seemed to work for me. Unfortunately, I don't see putting in some sort of fix just for thinkorswim.app, since it's a one-off case.

**Comment by tmaneri** [comment]
Ok, I’ll try that out. I had a feeling it might be a bug on the other end,
but was hoping it could be fixed so I can use both in harmony. No worries
though, just figured I would report it. Thanks!

**Comment by rxhanson** [comment]
Right, thanks for reporting it, regardless. Looks like thinkorswim users have reported similar issues with magnet (https://www.reddit.com/r/thinkorswim/comments/dzou4c/think_or_swim_beachball_of_death_mac/), as would be expected since it most likely performs macOS calls/operations similar to Rectangle.

With all that said, if there were a passionate thinkorswim user that created a pull request to handle this scenario elegantly then I would be inclined to consider it. Disabling the click listening when thinkorswim is frontmost still sets the app up for odd behavior since you might drag to snap a window other than one belonging to thinkorswim. There's not really a "great" solution in my opinion.

I'm going to go ahead and close this one out since I don't have plans to fix it, and rename it so that it's less generic.

**Comment by tmaneri** [comment]
@rxhanson thanks for the help. I just disabled "Snap windows by dragging" (I didn't really use this anyways) and no more issues. 👍

**Comment by helgridly** [comment]
I'm late to the party here but just wanted to say thanks for the "disable snap windows by dragging" suggestion. I've been banging my head against this for a while. In my case it also turned out that [RedQuits](http://www.carsten-mielke.com/redquits.html) was *also* causing similar issues so all the quitting Rectangle in the world didn't help me. I'm putting in a support ticket with ToS pointing them here in the hope they'll be able to figure something out.
