### ISSUE TITLE
automatic placement of maximized windows on the screen

### ISSUE THREAD

**Issue by mnahum** [rxhanson/Rectangle#235]
I just want to share the idea, 2, 3 or 4 windows maximized on the screen... I click and they are automatically position on the screen... vertically (my prefered way), horizontally or at corner... 
hope it seed an idea...

**Comment by rxhanson** [comment]
Thanks for sharing. There are some technical limitations, and some technical design choices in Rectangle that make it rather difficult to change multiple window positions with a single command. 

Closing this one out since I don't plan on adding this one in. If someone creates a PR for it, I would consider it.

**Comment by gennaios** [comment]
This is also something I would like. Perhaps such is possible with the current app? For example if there are anywhere from two to six or eight windows, evenly arrange them on screen, perhaps sorted by window title.
