### ISSUE TITLE
Export user settings for Rectangle

### ISSUE THREAD

**Issue by 1alessandro1** [rxhanson/Rectangle#247]
Hi, could you please add the option to export user settings once the keyboard shortcuts are customized?

Thank you.

**Comment by rxhanson** [comment]
User settings are stored in NSUserDefaults, which can be accessed as noted in the readme: https://github.com/rxhanson/Rectangle#preferences-storage

A better user experience would be to provide an import/export capability directly within the app, as noted in this issue: https://github.com/rxhanson/Rectangle/issues/190

Closing this one out since https://github.com/rxhanson/Rectangle/issues/190 will track that.
