### ISSUE TITLE
A rare bug.

### ISSUE THREAD

**Issue by Oleg-Chashko** [rxhanson/Rectangle#260]
macOS version: 11.0.1 Beta (20B5022a)
Rectangle version: 0.37 (42)
logs: 
[Logging.rtf.zip](https://github.com/rxhanson/Rectangle/files/5502293/Logging.rtf.zip)
[Bildschirmaufnahme 2020-11-06 um 17.07.02.mp4.zip](https://github.com/rxhanson/Rectangle/files/5502296/Bildschirmaufnahme.2020-11-06.um.17.07.02.mp4.zip)
The application stops working. Window sync breaks occur. Old bug. This bug rarely happens.

**Comment by rxhanson** [comment]
Thanks for reporting with the logs and the video. This is the macOS issue listed on the readme here: https://github.com/rxhanson/Rectangle#window-movingresizing-appears-animatedsmooth-instead-of-quick-and-windows-dont-end-up-where-you-expect

Here's the only issue I've left open regarding this, and it's for filing a bug with Apple: https://github.com/rxhanson/Rectangle/issues/165

Closing this one out since it's already documented.
