### ISSUE TITLE
Latest VS Code Update Overrides Binds

### ISSUE THREAD

**Issue by meeoh** [rxhanson/Rectangle#261]
macOS version: 10.15.17
Rectangle version: 0.22 (26)
VS Code Version: 1.51.0

As of this update, it seems like rectangle does not work when VSCode is the active application. I think maybe VSCode might have added their own keybindings that overlap with rectangle (e.g command + option + f). Not sure if this is something to override from rectangle or its something I need to go into VSCode and disable
logs (In Rectangle menu, hold option, "View Logging..."):

**Comment by rxhanson** [comment]
Shortcuts that overlap with the latest version of VSCode are working fine for me. I think that this is just "the usual" VSCode issue that is typically fixed by restarting VSCode. https://github.com/rxhanson/Rectangle/issues/43, https://github.com/rxhanson/Rectangle/issues/108, https://github.com/rxhanson/Rectangle/issues/182 

If the issue persists, please file a bug with VSCode as there is nothing that can/will be done Rectangle side.
