### ISSUE TITLE
Is there a way to add ability to full screen on custom shortcut?

### ISSUE THREAD

**Issue by ishaiMeresman** [rxhanson/Rectangle#27]
Hi,
First of all, great work developing this. It's definitely needed.

I wanted to know if it's possible to add the ability to configure a shortcut to make the current active window full screen.
I'm not so familiar with developing for Mac OS but found this:
https://developer.apple.com/documentation/appkit/nsview/1483780-enterfullscreenmode

I wonder if any of you can implement it as a feature,
Thanks,
Ishai

**Comment by rxhanson** [comment]
Ctrl+cmd+f is the default shortcut for this on macOS. I assume this is configurable in system prefs: keyboard: keyboard shortcuts. I’m away from my Mac so I don’t know for sure. I don’t have any plans to implement this since it’s just built in Mac behavior either way.

**Comment by rxhanson** [comment]
Quick follow up since I finally got back to my Mac. You can customize the shortcut for full screen in macOS, and I have a quick write-up that covers how to do it here: 
https://medium.com/ryan-hanson/going-without-a-3rd-party-window-manager-in-macos-catalina-4bd270b29245

**Comment by sglbl** [comment]
@rxhanson I think having fullscreen shortcut on Rectangle would be really helpful.

Now after many years, on macOS Tahoe 26, Apple already provides many shortcuts related to window sizes.

<img width="634" height="597" alt="Image" src="https://github.com/user-attachments/assets/cee7345b-b87e-4101-9489-20ac40b1d14a" />    
 

**Mac Built-in Shortcuts:** Control + Fn
**Rectangle Shortcuts:** Control + Option

**Fullscreen Shortcut:** Control + Command + F

MacOS doesn't provide maximize shortcut (and most of its shortcuts conflict with apps like chrome/vscode..) so I am dependent on Rectangle, but anytime I want to use maximize or fullscreen shortcuts I am confused and using the wrong sequence.  
I believe Rectangle should support a shortcut for fullscreen too, maybe just Control + Option + F. Otherwise I believe it's so confusing.

**Comment by whusnoopy** [comment]
@rxhanson WWould you consider adding a "Fullscreen" shortcut to Rectangle?

In recent macOS versions, Apple switched the default shortcut from `Ctrl+Cmd+F` to `Globe (Fn) + F`. However, most external keyboards lack a dedicated Globe key, and remapping a key to Globe via QMK/VIA isn't easily supported (often requiring third-party tools like Karabiner-Elements). Having built-in fullscreen shortcut support in Rectangle would make window management much smoother on external keyboards.

**Comment by sglbl** [comment]
> In recent macOS versions, Apple switched the default shortcut from `Ctrl+Cmd+F` to `Globe (Fn) + F`. However, most external keyboards lack a dedicated Globe key, and remapping a key to Globe via QMK/VIA isn't easily supported (often requiring third-party tools like Karabiner-Elements). Having built-in fullscreen shortcut support in Rectangle would make window management much smoother on external keyboards.

Definetely, also Globe (Fn) + F keybinding creates problems on many apps such as VS Code, it writes the letter f and then toggles fullscreen which is unwanted.

**Comment by rxhanson** [comment]
I'll merge a pull request that adds this into the Extras button popover on the General tab.

**Comment by sglbl** [comment]
> I'll merge a pull request that adds this into the Extras button popover on the General tab.

Thank you. I would love to see **⌃⌥ F** (`Control + Option + F`) as Fullscreen shortcut

**Comment by Cingirakli1Dumbelek** [comment]
> I'll merge a pull request that adds this into the Extras button popover on the General tab.

Hi, when will this feature be released?

**Comment by rxhanson** [comment]
Thanks for asking. My current focus is reworking the Settings window to better accommodate more settings such as this one. After that's done, if anyone wants to make a good PR with this functionality then I'll merge it in.
