### ISSUE TITLE
FR: resize windows to horizontal fourths

### ISSUE THREAD

**Issue by jpchen** [rxhanson/Rectangle#276]
I'm trying to use rectangle for a 49" but its preset defaults don't divide the screen nicely. Given the popularity of ultrawide monitors, it would make a lot of sense to have the ability to hotkey dividing into fourths across the width of the screen.  If feature requests aren't being considered, are there commands to manually customize this? Thanks.

**Comment by rxhanson** [comment]
I don't have plans to add in more window sizes to Rectangle at the moment. I would consider a pull request that adds in the desired window sizes.

>  are there commands to manually customize this?

There's not a command line or scripting interface for Rectangle, if that's what you're looking for. Mainly this is because there are other free open source solutions out there; try Hammerspoon.

Shameless plug for my paid app, [Hookshot](https://hookshot.app): It has a custom shortcut builder (the wrench & ruler tab), where you can build out any window size you want with a specified docking area, and additionally configure different window sizes/locations for repeated shortcut executions. It also contains Rectangle entirely, although with a different UI. 

Closing this one out since I don't have plans to implement it (but like I said, I would consider a PR).
