### ISSUE TITLE
Unable to record custom shortcuts

### ISSUE THREAD

**Issue by daveshirman** [rxhanson/Rectangle#299]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Big Sur
Rectangle version: Version 0.40 (45)

I am unable to record the shortcut: alt+cmd+left / right (left half / right half)
When I try it just doesn't record the shortcut.
I have enabled allow any keyboard shortcut & selected ignore Rectangle whilst I'm trying to register the commands.

Tried installing fresh several times.

Found this is because of the switching spaces in mission control being set in system preferences.  Imagine this app should warn or make the user aware of the conflict.

I am a dev and I didn't know what was wrong.  Normal people won't get it.

**Comment by rxhanson** [comment]
Thanks for reporting. 

Unfortunately, this isn't something that can be corrected from within this app (as far as I know). If a macOS registered keyboard shortcut is executed, then the keystrokes don't pass through the event stream to other applications. Your alt+cmd+left will only execute switch spaces and will stop there, so the shortcut recorder in Rectangle will not receive the keystrokes and will be unaware that you are attempting to assign those keystrokes.

Closing this one out since there's no changes to be made in Rectangle.

**Comment by daveshirman** [comment]
@rxhanson Ok that's useful info.  Perhaps a note/msg can be added to make that more obvious to the user though?
