### ISSUE TITLE
Thanks for your work and RFC

### ISSUE THREAD

**Issue by frederikhors** [rxhanson/Rectangle#305]
I'm coming from https://www.spectacleapp.com to yours.

Your project is amazing and I wanna thank your for your precious work.

Just a note: with Spectacle I could resize and move windows with **only my right hand**.

I have a MacBook:

![image](https://user-images.githubusercontent.com/41120635/102985654-ccef6880-450f-11eb-86a6-4a01879acc34.png)

Can you reconsider the default shortcuts (at least for 1/3 - 1/2 and full size) to use Command + Option instead of Command + Control?

Thanks again! :smile:

**Comment by rxhanson** [comment]
Sounds like you selected the "Recommended" Rectangle defaults instead of Spectacle defaults at first launch. If you click the reset default shortcuts button in the settings tab, you can select the Spectacle defaults instead.

**Comment by frederikhors** [comment]
Yeah I know. What I don't understand is why two ways. I think the Spectacle one can help using it with one hand only.

Am I wrong?

**Comment by rxhanson** [comment]
> why two ways

The default shortcuts started out as just Spectacle, since Rectangle was meant to be a drop in replacement for Spectacle. There's a number of spectacle default shortcuts that conflict with other applications, so I added the other set of defaults that I preferred and used, and allowed those to be configured via terminal command. I had a lot of users that kept requesting to allow those defaults to be set in the UI, because of the conflicts of the Spectacle defaults. I also kept getting requests for strange ways to work around the fact that the Spectacle defaults had conflicts. Long story short, this current setup gives both users that come from Spectacle and users that want to avoid conflicts what they want. I had inclination to just make the non-conflicting ones default and only allow the Spectacle shortcuts via terminal config, but there would have been a lot of unhappy Spectacle users :)
