### ISSUE TITLE
Steam resizing/positioning isn't working

### ISSUE THREAD

**Issue by pepablock** [rxhanson/Rectangle#318]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: **Big Sur v. 11.1 (20C69)**
Rectangle version: **0.41 (46)**
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): **—**

It seems that Steam.app client is somehow immune to the Recragle window resizing/positioning. When you try to center the window it goes back to its original position.

**Comment by rxhanson** [comment]
Thanks for reporting!

Unfortunately, from Rectangle's perspective, there's not really any changes that make sense to make specifically for this. 

I think Rectangle used to work fine with Steam, so perhaps something has changed in Steam. My recommendation is to file a bug with Steam.

Closing out since no changes will be made in Rectangle for this.

**Comment by stealthgyro** [comment]
Probably shouldn't comment on a close issue, but it is fascinating, it tried to go there, but Steam snaps right back...

Also it does this on Better Touch Tool (and better snap tool), pretty sure it does this on Spectacle... it's kinda crazy I don't know what Valve is doing to make the Steam window behave this way.
