### ISSUE TITLE
Repeatedly doing "Right Half" or "Left Half" will instead resize to different thirds

### ISSUE THREAD

**Issue by troyunverdruss** [rxhanson/Rectangle#32]
I used to use Spectacle, so I think this behavior is the same as that app, but it is not what is described in the docs or the help shortcuts. If I have a window active, like Firefox, and then do "Right Half" repeatedly, it will do the following: first click, resize to right half of window, second click, it will take up the right 2/3s of my screen, third click:  it will take up 1/3 of my screen, fourth click: back to only 1/2 of my screen. 

With the new explicit thirds shortcuts, I would like to disable the different thirds resizing when using the "Half" shortcuts. This seems like it's at least documented incorrectly, possibly it's a real bug. And depending on that, this could be a feature request or a bug report.

**Comment by troyunverdruss** [comment]
Update: I'm using the latest version of Rectangle (Version 0.10 (14)) and latest version of MacOS (Version 10.15.1 (19B88))

**Comment by rxhanson** [comment]
This behavior purposefully exists in Rectangle specifically because it existed in Spectacle, and I wanted Rectangle to be a near drop-in replacement. Sure, it could be documented more. 

To disable this behavior, there is a hidden config that can be set with the following terminal command:
`defaults write com.knollsoft.Rectangle subsequentExecutionMode -int 2`
Followed by a restart of the app.

Note that the `subsequentExecutionMode` is also tied to the setting for traversing displays in the prefs, so don't touch that setting.

**Comment by rxhanson** [comment]
I added this info into the Readme, so I'm going to close out this issue. If you have further issues or don't feel everything's addressed, feel free to comment or reopen. 

If there's enough people that don't like the default behavior, I'll consider adding a checkbox for managing it in the prefs.

**Comment by troyunverdruss** [comment]
Makes total sense, thanks for the tip on `defaults write`.  Also big thanks for putting this together and keeping the window management dream alive :)
