### ISSUE TITLE
Testing on El Capitan

### ISSUE THREAD

**Issue by amandamana** [rxhanson/Rectangle#35]
I'm trying to test on OS X 10.11.6 but I can't authorize Rectangle in Accessibility. I think this is because the Finder has placed a grey do-not-enter symbol over the icon and I'm having to run the Rectangle.app/Contents/MacOS/Rectangle executable from the terminal. After a while Rectangle exits with:

> dyld: lazy symbol binding failed: Symbol not found: _os_log_type_enabled
>   Referenced from: /Volumes/HD/Rectangle.app/Contents/MacOS/../Frameworks/libswiftos.dylib
>   Expected in: /usr/lib/libSystem.B.dylib
> 
> dyld: Symbol not found: _os_log_type_enabled
>   Referenced from: /Volumes/HD/Rectangle.app/Contents/MacOS/../Frameworks/libswiftos.dylib
>   Expected in: /usr/lib/libSystem.B.dylib
> 
> Trace/BPT trap: 5

**Comment by rxhanson** [comment]
Thanks for testing it out on El Capitan! 

I've updated Rectangle to allow it to be run on El Capitan in v0.11: https://github.com/rxhanson/Rectangle/releases/tag/v0.11

Please try that version out and let me know how it works. If you don't mind, it would be awesome to know if window snapping, keyboard shortcuts, and selecting actions from the menu all work.

**Comment by amandamana** [comment]
Thanks for the new release! v0.11 runs fine on OSX 10.11.6. The console log shows no complaints. Selecting actions from the menu, keyboards shortcuts, and re-assigning them, all work.

I don't know how the snapping feature is supposed to work, but it doesn't seem to do anything. It sounds like something I would turn off anyways.

The traverse displays option is great and something I will use all the time!

The Bottom Half command is unreliable on my 2048 x 1152 display. It seems to only work properly when the initial window position is set to Top Half. Otherwise it resizes the window to half width and 70-90% height aligned to the bottom left corner.

The Bottom Half command works properly on my 1080 x 1920 display so I doubt this is an El Capitan issue. My display arrangement may be important: a T laying on it's left side. Spectacle did not have this issue.

Rectangle and Spectacle both use around 50 MB memory at launch. After 5 minutes Spectacle drops to under 10 MB, while Rectangle stays around 25 MB.

**Comment by rxhanson** [comment]
Thanks for the details!

> I don't know how the snapping feature is supposed to work, but it doesn't seem to do anything. It sounds like something I would turn off anyways.

If you're a "use the mouse only if I really have to" type of person, you'll be just fine without window snapping. Here's a video somebody put up on youtube that does show how the window snapping works - it's toward the end. https://www.youtube.com/watch?v=17t0OSziUgY 
You drag a window until the mouse cursor reaches an edge of the display, and then release. 

> The Bottom Half command is unreliable on my 2048 x 1152 display. It seems to only work properly when the initial window position is set to Top Half. Otherwise it resizes the window to half width and 70-90% height aligned to the bottom left corner.

> The Bottom Half command works properly on my 1080 x 1920 display so I doubt this is an El Capitan issue. My display arrangement may be important: a T laying on it's left side. Spectacle did not have this issue.

The fact that it works properly when the initial window position is set to top half actually does point to some odd behavior within El Capitan (although I could be wrong). From Rectangle's perspective, window actions are not dependent on the current size/location of the window in that way. In writing Rectangle, I only kept logic from Spectacle that from my testing made sense to keep in - so chances are that Spectacle may have had some logic built in to handle weird behavior from certain macOS releases.

An unfortunate circumstance of running on El Capitan is that my debug logging (via os_log) was the only thing in code not supported going back that far, so I'll have to add NSLog in it's place so that we can get some more insight as to what's going on. That'll come into the next release - I'll keep this issue open and use it to track this.

> Rectangle and Spectacle both use around 50 MB memory at launch. After 5 minutes Spectacle drops to under 10 MB, while Rectangle stays around 25 MB.

Thanks for that observation. I did some pretty thorough memory testing a few months ago, and basically here's my takeaway. The initial high memory usage is the use of the GUI, which brings the memory usage to pretty much the same for both apps (as you observed). If you don't open the prefs at all on either app, they were both around 10MB for me. So, what's going on with Rectangle not releasing the memory for the GUI? The more I dug into this, the more I didn't want to touch it. Perhaps it's something about my GUI (using MASShortcut), or perhaps it's something with Swift? At any rate, if I manage the memory myself, I can drop the memory usage, but window memory is ultimately handled by macOS and it decides when to actually release everything dealing with the window. When deallocating the memory for the window, not all of it would be released. If a user reopened the window, that unreleased portion would still exist, and the new window would also be there. So if a user reopened the window multiple times, there would be some sort of inherent memory leak. Perhaps macOS would clean all of this up at some point, but I preferred not cleaning up the window manually so that I could avoid that leak altogether. There are tools for finding leaks, but I think this goes a little deeper with macOS window memory management. Of course, it all felt a little like splitting hairs for 15MB of memory this day and age, too.

I'll post back here when I get another release ready, and if you don't mind testing it out again, that would be awesome.

**Comment by rxhanson** [comment]
Alright, the new release is up: https://github.com/rxhanson/Rectangle/releases/tag/v0.12

Here's the steps for viewing logs:
https://github.com/rxhanson/Rectangle#view-debug-logging

When you get a chance, paste some logs in here with the erroneous behavior and I'll see if we can figure out what's going on.

Thanks!

**Comment by rxhanson** [comment]
Doing some housekeeping and gonna close this out now that debug logging should be present in El Capitan. Please file any bugs to new issues and provide logs as necessary.

Thanks!
