### ISSUE TITLE
Rectangle ignores first mouse edge event after some time has elapsed

### ISSUE THREAD

**Issue by yunuserkaya** [rxhanson/Rectangle#355]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Big Sur
Rectangle version: 0.42

https://user-images.githubusercontent.com/22533048/105569809-ccf2ac00-5cf9-11eb-9179-92d4d243ef08.mov

**Comment by rxhanson** [comment]
I think that the issue here is that the logic to obtain an identifier for the window is not being grabbed the second time that you have tried here. It could be due to really quick movement of the window.

Getting the identifier of the window is necessary in order for the history of Rectangle window commands to be associated properly with the window. There might not be any way to always obtain the window identifier, which means there could be a tradeoff built into the app where you could disable all features that require the history when using drag to snap. Potentially, there could be a better way to uniquely identify a window.

 I'll plan on leaving this issue open until I decide a path forward.

**Comment by rxhanson** [comment]
I finally got a chance to dive into this one, and the issue surprisingly isn't grabbing the window id, it's actually a macOS side issue. In order to determine if a window is being moved, Rectangle will ask macOS for the origin of the window and compare it to the initial origin (typically from when the down click occurs). In this scenario, where the mouse is moved quickly, macOS will respond with the same origin repeatedly instead of the actual updated origin of the window. It's nice to know what's causing the issue, but unfortunately since it is Apple side, this means that the likeliness of it getting fixed is so low that I'm not even going to bother creating an issue for it. I don't have a good idea for a workaround, but if you know of any apps that don't exhibit this issue then let me know and I'll give it another look.

Not trying to use this issue as a platform for marketing my paid app, but with [Hookshot](https://hookshot.app) I personally don't snap my windows by dragging anymore. For a user that would be impacted by this issue, Hookshot might be worth looking at.

**Comment by yunuserkaya** [comment]
What is the service you use to determine if the window is moved?
Is the problem statement: macOS responds with incorrect original window origin if window is moved too fast ?
I can file a bug report for you.

**Comment by rxhanson** [comment]
In v0.43, I added a little bit of code to make it so this might happen a little bit less depending on how you use it. If you quickly drag and drop (mouse button up) on an edge, then there is some chance that the api will return that the window moved, and the snap event will get fired. Obviously still not great, but a slight improvement.

> What is the service you use to determine if the window is moved?

Rectangle (and all window managers) rely on the Accessibility API to both obtain window information for other apps and execute the move/resize commands. 

> Is the problem statement: macOS responds with incorrect original window origin if window is moved too fast ?

The original window origin (location) is accurate, but the window origin while the window is being moved is not. It is returned as the original window origin. When a user is dragging a window, Rectangle is listening to mouseDragged events from the event stream, and just listening to those events might be what is preventing the Accessibility API from providing back the proper window origin. Or it could just be that sometimes the Accessibility API has some time lag before it will update its values for window origin as it probably wasn't built with this use case in mind.

This type of issue is most certainly low enough priority to Apple that I would not get hopes up on receiving a fix.

**Comment by rxhanson** [comment]
Closing this one out since I do not see good solution implementable in Rectangle at this time. As mentioned, if you come across another window manager that somehow got around this issue then let me know and I will revisit it.

**Comment by yunuserkaya** [comment]
This is because the accessibility API ends up asking the NSWindow in the app for its origin, and window drags are done server-side and the app only updates its position every 100ms.
