### ISSUE TITLE
Icon shadow in menu bar should be removed - especially on non primary display

### ISSUE THREAD

**Issue by jutsto** [rxhanson/Rectangle#366]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.1
Rectangle version: 0.42 (47)
![image](https://user-images.githubusercontent.com/5179559/106311126-7dd8d980-6219-11eb-8606-5bf14229ade3.png)

There is a drop shadow on the rectangle icon in the menu bar. It is not very noticeable on the primary monitor, but on the secondary (or unselected) display it is not right and doesn't match other icons. See image attached. To match OS style, the drop shadow should be removed.

**Comment by rxhanson** [comment]
Looks like Apple fixed this in macOS 11.2. I don't see it anymore.

**Comment by jutsto** [comment]
I'm running 12.2 and still see it.  It's shows-up on the secondary (non-active) monitors only.

**Comment by rxhanson** [comment]
Ah, so I think it is desktop picture dependent (it goes away with some). This is an Apple side bug, since there is no shadow as part of the icon and nothing really unusual about it. There might be a workaround, but it would probably take some blind playing around with the icon to figure it out. I'll leave this open in case anyone wants to take it up.

**Comment by rxhanson** [comment]
Try out v0.43 and let me know how that looks for you.

**Comment by jutsto** [comment]
Interesting... it is still there on the non-dominant monitor, but less visible now:
<img width="211" alt="image" src="https://user-images.githubusercontent.com/5179559/107887711-ee8c2100-6ebc-11eb-9e72-dd03fa66a80b.png">

**Comment by rxhanson** [comment]
This appears to me to be the "intended" functionality from Apple. As mentioned, I'm not adding this shadow - it's being done by macOS, new in Big Sur and it does not correspond to the shape of the icon. The shadow is displayed relative to the image size, so changing the icon to be a little bit smaller is what updated the shadow size. It is strange to me that Apple wouldn't make the rest of their icons have the shadow, too. There might be a way to get rid of the shadow by changing it so that it is not "template" and making light and dark mode versions of it. The convention I've typically seen everywhere is to use template icons so that light and dark mode are automatically handled. Closing this out since I don't think I'll dig around in this further, but if anyone else wants to try it out then feel free.
