### ISSUE TITLE
Cant create shortcuts like CTRL-<Arrow>

### ISSUE THREAD

**Issue by csm10495** [rxhanson/Rectangle#398]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.2.2
Rectangle version: 0.43

For some reason when i try to record a shortcut (for something like left half) with CTRL-Left (or any other arrow key) it doesn't seem to register the arrow key, so it can't create the shortcut.

**Comment by rxhanson** [comment]
Ctrl+arrow key is already bound by macOS for switching spaces, which is why Rectangle's shortcut recorder won't bind it. 

Have you tried going into System Prefs -> Keyboard -> Shortcuts -> Mission Control and removing the Mission Control shortcuts?

**Comment by csm10495** [comment]
Cool beans that worked for ctrl-arrow!

What about doing something like CTRL-<LEFT>-<UP>? 
Basically I'd like CTRL-Left to be left half then CTRL-LEFT-UP to be upper left corner.

**Comment by rxhanson** [comment]
Glad that worked!

Rectangle uses the keyboard shortcut registry in macOS (via the shortcut recorder MASShortcut). This API only allows for one non-modifier key to be registered as a shortcut. In order to have multiple non-modifier keys registered, Rectangle would have to listen to keystrokes. This would add a decent amount of complexity to the app, and I like that it doesn't listen to keystrokes. As such, this isn't something I would consider adding to Rectangle but might think about it for my paid app, Hookshot (https://hookshot.app), since I have received this request multiple times. Hookshot does already have the option for the Windows behavior where you can do a left then up to get top left.

Closing this one out since no action is required Rectangle side (notifying the user of a failed keyboard shortcut recording due to macOS registered keys is not possible).
