### ISSUE TITLE
Cannot perform actions on VS Code window

### ISSUE THREAD

**Issue by ERElli** [rxhanson/Rectangle#43]
macOS version: 10.14.6
Rectangle version: 0.10 (14)

As title says, VS Code does not respond to commands from Rectangle. All options are greyed out when VS Code has focus

**Comment by rxhanson** [comment]
I use VSCode for some of the things I work on, and I haven't had any issues. 

If all options in Rectangle are grayed out, that means that Rectangle can't grab the frontmost window using the accessibility API. This usually happens when the "window" in front is something that can't be focused or grabbed via accessibility (not typical of a normal VSCode window from my experience). Do you have something special about your VSCode setup, or are you opening the Rectangle menu when the main VSCode window is not in focus?

Also, keyboard shortcuts in VSCode can conflict with global keyboard shortcuts. You'll want to be sure that you don't have conflicts there.

**Comment by rxhanson** [comment]
Closing this out since I can't reproduce it. If you have more details to add that can help pinpoint this down, feel free to reopen with more info. v0.12 makes it a lot easier to grab debug logging, and that might help (check out the readme).

**Comment by ERElli** [comment]
Sorry for taking so long to get back to you. I'm not entirely sure why, but restarting VSCode fixed the issue

**Comment by rxhanson** [comment]
No worries, thanks for replying. 

Restarting VSCode working might mean that there was a keyboard shortcut conflict, but there's not a good way to tell for sure. When the app was closed the shortcuts associated VSCode would unregistered from macOS and that might have forced macOS to clean up the registered shortcuts. VSCode might do some weird stuff with their shortcut registering since it seems like a lot of people using Spectacle had issues with it.

**Comment by franzejr** [comment]
I got the same issue with VSCode and I came here to say that. I don't know what is happening, but when I restarted it just worked.

**Comment by PhillipFraThailand** [comment]
Experienced it too, i am working in two project simultaneously but its only one project, and always the same, that is not responding to shortcuts

**Comment by stephenWithVincent** [comment]
I updated my version of VS code and it started to work again

**Comment by Lukas238** [comment]
Can confirm that started working again after I apply the pending vsCode update and restart it.

**Comment by toughyear** [comment]
If you are launching VsCode using a terminal like `warp` it may lead to this bug. Try launching the app but not from terminal and see if it works.

**Comment by yairhaimo** [comment]
> If you are launching VsCode using a terminal like `warp` it may lead to this bug. Try launching the app but not from terminal and see if it works.

Yep. Warp was the problem for me. Thanks!

**Comment by bhavul** [comment]
I'm still facing this. Restart didn't fix it, neither did updating vscode. Anyone else? 
It's super frustrating.

**Comment by peterlundberg** [comment]
This happened to me recently as well after a reboot of my MBP

Closing and starting code again solved the problem (developer reload window did not)

**Comment by alliv8** [comment]
same here, reloading vs code fixed it

**Comment by benji011** [comment]
Just to add that restarting Rectangle fixed the issue for me (and not restarting VSCode)

**Comment by yashcrest** [comment]
> Just to add that restarting Rectangle fixed the issue for me (and not restarting VSCode)

was the options in rectangle greyed out for you when VS code was the active window ?
