### ISSUE TITLE
Rectangle (and Magnet aswell) break Preview app in MacOS 11.3

### ISSUE THREAD

**Issue by Muzosh** [rxhanson/Rectangle#455]
Hey, I just wanna let developers know, that Apple did something in MacOS 11.3 update, which eventually make Preview app unusable.

As it turns out, the "innocent culprit" is Rectangle in my case. This was found out by a user, which also reported this problem with Magnet app aswell as with Rectangle.

Here is link to my original post a few days ago about the problem: [macforums](https://forums.macrumors.com/threads/preview-app-not-responding-after-searching-and-clicking-back-into-the-text-after-macos-11-3.2294289/)
As you can see, quite a few people were able to reproduce this problem on MacOS 11.3.

I have posted this on [Apple Community](https://discussions.apple.com/thread/252721698?page=1) aswell, where user CleffyHeft found out that info about window management apps being a culprit here.

Worth to mention is one comment on the MacForums link, where user LuisN reports that **this problem is NOT reproducible in MacOS 11.4 Beta. So I guess this ticket is not a request to fix a bug**, but I think it's still worth to post here, in case devs might be able to debug this and find out the real problem.

Sorry if this issue is not worth to be issue, feel free to close this anytime.
Best regards,
Muzosh.

**Comment by rxhanson** [comment]
Thanks for the post. As you mentioned, it's probably not something I will make any code changes for since Apple appears to have put in a fix. 

Without testing anything out, I am pretty sure that the issue is just Rectangle listening to clicks on the event stream, which is necessary for the snap windows by dragging to screen edges feature. To use Rectangle with preview in 11.3, you can uncheck the box for "snap windows by dragging", and it should work fine.

**Comment by Muzosh** [comment]
Thanks for the info, unchecking "snap windows by dragging" really works. I will keep it unchecked until this is fixed in MacOS 11.4

**Comment by Muzosh** [comment]
(I will keep this issue open for a while if that's ok, maybe someone will want to add comments with their investigation?)

**Comment by Muzosh** [comment]
I can confirm that this issue has been solved by Apple in MacOS 11.4. :)
