### ISSUE TITLE
Saving JSON setting freezes

### ISSUE THREAD

**Issue by jiangtianli91** [rxhanson/Rectangle#477]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.3.1 (20E241)
Rectangle version: 0.46 (51)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): Does not provide logging information

The window for saving json setting files is extremely slow. It almost freezes even to change the file name.

**Comment by rxhanson** [comment]
I experience this, too, but apparently most users do not. The strange thing is that there's nothing unusual about the open/save prompts in Rectangle, and I use the identical code in my other apps and they have no issues. At first I thought it was a sandbox thing, but one of my other apps that doesn't have this issue is not sandboxed either.

**Comment by PatrickF1** [comment]
I also experience too for both saving and importing.

**Comment by rxhanson** [comment]
Alright, got this one figured out. It is fixed in v0.47, out momentarily.

**Comment by rxhanson** [comment]
If anyone experiences this in v0.47+, feel free to reopen or comment.
