### ISSUE TITLE
Window centres when moving to next display

### ISSUE THREAD

**Issue by russellgreenwood** [rxhanson/Rectangle#481]
Not sure if I'm missing something, but when I push a window to the 'next display' or 'previous display' it centres on the next display vs. Spectacle behaviour which was to put it in the exact same place (eg. right third) on the new display. 

macOS version: 11.4
Rectangle version: 0.46

**Comment by rxhanson** [comment]
Centering the window when moving it to the next/previous display is functionality that comes directly from Spectacle. Here's the Spectacle code that does this:
https://github.com/eczarny/spectacle/blob/master/Spectacle/Resources/Window%20Position%20Calculations/SpectacleNextOrPreviousDisplay.js

The reason why I haven't added in this type of behavior into Rectangle is because to do it properly in full would make some assumptions about user expectations, window sizes, and window placement that might end up being more ambiguous than just centering. I'll consider some changes in a future release for handling some of the cases that wouldn't end up ambiguous, though.

**Comment by russellgreenwood** [comment]
Woah.  OK, I have totally remembered that functionality differently in my mind, just pulled out old Spectacle to reproduce and realised I was wrong.

Apologies for the time waste.
