### ISSUE TITLE
Cannot map cmd+ctrl+option+shift+q

### ISSUE THREAD

**Issue by onemanstartup** [rxhanson/Rectangle#49]
macOS version: Catalina
Rectangle version: 0.12

I checked "Allow any shortcut"

I am mapping keyboard with super modifier.
```
q w e
a s d
z x c
```
I used those shortcuts in the past with slate in the past. 
If it's not possible to do. Can I suggest a feature. It would be cool if with one shortcut I could rotate window around the clock in the corners. Then there wouldn't be a need for a multiple corners shortcuts (at least it will free multiple keybindings).

Thanks.

**Comment by rxhanson** [comment]
I'm actually not sure why [MASShortcut](https://github.com/shpakovski/MASShortcut) will not accept that, but my guess is that there's something in macOS that is preventing it. Unfortunately, this would require a change in the MASShortcut source. You're welcome to file a bug there and I'll update the version of MASShortcut in Rectangle if they accept a change for it.

For the feature request, I don't have the bandwidth to add that currently, but I'd definitely consider a pull request with that functionality.

Closing this one out since it is not immediately fixable in Rectangle.

**Comment by connorch** [comment]
I'm a little late to the party, but I use a similar configuration to @onemanstartup and was able to find a workaround in case future users are looking for a solution.

I used Karabiner-Elements to remap cmd+ctr+option+shift+q to cmd+ctr+option+q, then using that shortcut in Rectangle.  Now the shortcut works fine. 
_Tested on macOS Monterey with Rectangle v0.49._
