### ISSUE TITLE
Window didn't snap back when the window is moved after a command is hit

### ISSUE THREAD

**Issue by ZhongxuanWang** [rxhanson/Rectangle#503]
- [Yes] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.4
Rectangle version: Latest, 0.47 (52)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

I'm not sure if it is a bug or a feature request, but after I hit shortcuts to, for example, let the window snap to 1/2, but then I moved the window away from the position of 1/2. However, after I hit the same shortcut again, I would expect the window to be snapped back to 1/2 again since the window has already moved to another position, but instead, the window snapped to 1/3. 

I think there only needs to add mechanism when detecting repeated commands, before going to the next action, the app checks whether the window has moved.

Thank you! :)

**Comment by rxhanson** [comment]
Thanks for reporting. What you're describing is indeed a bug.

Just to confirm: You have "Restore window size when unsnapped" unchecked, correct?

**Comment by ZhongxuanWang** [comment]
Correct :) And moreover, the problem appears when I used the shortcut to position the window, not when I used the snap feature. 

Thank you, and I'm looking forward to updating the Rectangle soon!

**Comment by lethargosapatheia** [comment]
Closely related to this: when I snap a window to any side/corner and I drag it away faster (that is to say, not holding the arrow very long on the top bar while unsnapping/dragging the window to another place), the initial size is not restored. This is consistent. I can reproduce it every time.
I would love it if the window restored properly even when moving it faster. That's basically the only thing missing from this software. Everything else seems great :)
(Macbook Pro 13 M1 2020, Big Sur 11.4 and on a Macbook Pro 15 2015, macOS Catalina)

Is it worth issuing a separate bug report for this? It is related to this in my opinion, but the context is slightly different, because there's no intermediate action (pressing a key or something to that effect).

**Comment by rxhanson** [comment]
@lethargosapatheia 
> Is it worth issuing a separate bug report for this? It is related to this in my opinion, but the context is slightly different, because there's no intermediate action (pressing a key or something to that effect).

Can you create a different bug report for this? It is not the same, and the reason it exists is due a delay in macOS where Rectangle is unable to obtain window information when the window is quickly dragged. Working through that bug means identifying some sort of workaround.

**Comment by ZhongxuanWang** [comment]
I just realized there's a new update pushed, and after I installed it everything worked fine! A great thanks to you @rxhanson  for keeping everything working smoothly! :)
