### ISSUE TITLE
Restoring window size by unsnapping causes window moving away

### ISSUE THREAD

**Issue by awx-dylan-xie** [rxhanson/Rectangle#516]
I checked the "Restore window size when unsnapped" option, and snap the window _**from a small size to a bigger size**_, say full screen. When I try to unsnap the window by moving the window away _**with pointer hanging at far right of the bar**_, the window restores its original size, but _**drifts away to left hand side**_, leaving the pointer hanging on nothing. The pointer is still controlling the window's position though. It seams like in such cases, the window restores size in accordance to its upper left corner's coordinate, and thus shrinks small to left hand side, when the pointer is still on the right hand side.

PS. This restoring functionality is not always functioning.

- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.4
Rectangle version: v0.48(53)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): N/A

**Comment by rxhanson** [comment]
This bug has existed since the beginning of Rectangle, and the result of my initial investigation is that unfortunately there is not a good way to fix it. Adjusting the window location to the cursor location typically results in really janky window behavior. The better solution is to leave it as it currently is.

If anyone else wants to investigate it and finds a better solution, I'd definitely consider a PR for it.

The restore functionality not always working is also some flaws with the macOS API, and it is typically exposed with moving windows quickly. There might be a workaround for this, something I plan on looking into in the next release.

**Comment by rxhanson** [comment]
Housekeeping and closing this one out since it's primarily macOS side and there's nothing reasonable that I'm aware of Rectangle side for fixing it.

I took another look at the restore functionality not always working and this is also something that is more macOS side and doesn't make sense to me to address within Rectangle. If you come up with a good way to reproduce it, let me know and I can take a look again.
