### ISSUE TITLE
Dragging a maximized window should restore the windows size if the option is enabled

### ISSUE THREAD

**Issue by jwallet** [rxhanson/Rectangle#541]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: macOS Big Sur v11.4
Rectangle version: version 0.48 (53)

Thanks for making this awesome addon, it's really a great tool to have.

But, I'm experimenting something weird with "snapped/maximized" windows. when using the setting `Restore window size when unsnapped`, I was expecting to also work with maximized window but it does not. So I'm not sure if it's a bug or it's because I use BigSur update.

Would it be possible to include not only snapped window but also maximized windows to this feature so I don't have the behaviour shown here (does not restore to original size)?:

By the way, snapping does not always work so it's faster to double click the header to maximize it

![capture](https://user-images.githubusercontent.com/23088305/130154450-3bbbc5ab-9f2b-416c-a21a-d7d305103688.gif)

**Comment by rxhanson** [comment]
This comes down to Rectangle not being able to be notified when a window is maximized outside of Rectangle. Without knowing this, Rectangle is not able to know what the window size is before the moment where it gets maximized. There might be some ways to work around this, but at first glance, I can’t think of a desirable one. 

Perhaps a better solution for your scenario is to adjust the snap area size to make the top snap area trigger farther from the top of the display. There’s a terminal command for it in the readme (I’m on my phone otherwise I would add a link)

**Comment by jwallet** [comment]
Ok I will look at it

**Comment by VandrerenErik** [comment]
> This comes down to Rectangle not being able to be notified when a window is maximized outside of Rectangle. Without knowing this, Rectangle is not able to know what the window size is before the moment where it gets maximized. There might be some ways to work around this, but at first glance, I can’t think of a desirable one.
> 
> Perhaps a better solution for your scenario is to adjust the snap area size to make the top snap area trigger farther from the top of the display. There’s a terminal command for it in the readme (I’m on my phone otherwise I would add a link)

but there is a "restore" feature that goes back to the previous size

**Comment by VandrerenErik** [comment]
I think this is no longer a problem, maybe this should be closed?

**Comment by rxhanson** [comment]
@VandrerenErik Sure, I'll close this out. I did have a request once to make the repeated execute for maximize be restore, but I kinda forgot about it - nobody else asked. just created a discussion for it (https://github.com/rxhanson/Rectangle/discussions/864)
