### ISSUE TITLE
Snapping  size is wrong for people with a side dock.

### ISSUE THREAD

**Issue by CodingWithDavidZ** [rxhanson/Rectangle#578]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.
- [ ] Could we add an option in preferences to add padding to the left (or right) for people who use side dock?

macOS version:
Rectangle version:
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):

**Comment by rxhanson** [comment]
If you’re using the macOS dock on the side, then this is likely a macOS bug that only happens immediately after the dock is hidden and displayed or a monitor is connected or disconnected. This is a bug that I don’t have plans to fix because it’s macOS side.

If you are not using a macOS dock and are instead using a third-party dock, then there are configurations that can specify gaps via terminal command. If this is the case then I am guessing this is a feature request for configuring this via the UI?
