### ISSUE TITLE
Continuous Integration for automated builds

### ISSUE THREAD

**Issue by GabLeRoux** [rxhanson/Rectangle#62]
I know you are not accepting new feature requests, but I think it would be nice to have automated builds for this project so you'd get all the benefits of knowing if a pull request is still building and passing tests.

I'm wondering if the project should use one of these:
* Github Actions
* Travis
* CircleCI
* Something else?

Here's some related documentation:
* Github Actions: https://medium.com/@jonnyburger/first-look-using-github-actions-for-building-ios-and-android-apps-4749609b96f0
* Travis: https://docs.travis-ci.com/user/reference/osx/
* CircleCI: https://circleci.com/docs/2.0/hello-world-macos/

I did not go into too much details on how you currently publish new versions and/or if you already have a CI setup somewhere, but I feel like this project would benefit from the above.

Thanks for making this amazing app :tada:

**Comment by rxhanson** [comment]
Saw your PR for this, thanks! 

I could write a pretty lengthy response about whether or not CI is actually necessary for this project, but what it boils down to is this:

- From a standpoint of what CI is intended for, there aren't really any benefits for this project at this time. The project is small and I'm the only dev, except for one time help from another dev (the rest are localization contributions). Publishing new versions is stuck being a somewhat manual process because I sign and notarize the app via Xcode (thanks, Apple) and then I upload a dmg to the github releases because it's the most logical place to look for it. I have some of this automated, and I'm sure there's ways to automate more of it, but it's not stuff that can be done via GitHub. 
- CI is good to have in that it makes the repo look more legit, and that can bring in more help.

Because of that first point, I haven't investigated my options, so I appreciate you laying them out for me and getting an initial PR in place. I'll give this a little more thought and see which route I'd like to take, based on it being useful from the perspective of the second point.

**Comment by rxhanson** [comment]
Went with Github actions - it's pretty sparse right now but might prove more useful if I offload more work to it.

Thanks!
