### ISSUE TITLE
Losing preferences after update

### ISSUE THREAD

**Issue by barbetb** [rxhanson/Rectangle#648]
First, thanks for this great product!

Little issue I encountered:
After updating to the new Rectangle version, I lost all my preferences and it was set to default settings again. Of course not a big problem, but a little annoyance. 

macOS version: Big Sur
Rectangle version: 0.49

Regards,

Rick

**Comment by sh-cho** [comment]
Did you happen to press 'Restore Default Shortcuts' button?

Because that button resets shortcuts even if you canceled. I fixed it but it's not released yet.

- https://github.com/rxhanson/Rectangle/pull/606

**Comment by rxhanson** [comment]
@barbetb thanks for reporting. This is a known issue also reported here: https://github.com/rxhanson/Rectangle/issues/419

Do you know which version you came from? I think this only happens from older versions before 0.44, since that’s around when I changed the format of how the shortcuts are stored. If it’s just from old versions, I probably won’t put in a fix since it would affect a small amount of users.

**Comment by barbetb** [comment]
Hi, I can't remember which version it was. It might have been an older one.

**Comment by rxhanson** [comment]
Doing some housekeeping and closing this one since a duplicate existed prior: https://github.com/rxhanson/Rectangle/issues/419
