### ISSUE TITLE
Unable to select shortcut

### ISSUE THREAD

**Issue by ekmartin** [rxhanson/Rectangle#661]
I'm trying to record a shortcut for "Right Half" of control-command-option-L but whenever I select it, the UI is just stuck at control-command-option and the L never shows up. It's not keyboard ghosting. Is the shortcut somehow used by something else? It doesn't give me the alert pop-up I normally get when I try to choose something that's used by a system key binding.

I'm using version v0.49 (54) in macOS Big Sur 11.6.

**Comment by rxhanson** [comment]
Sorry - not sure why I never replied to this one. Indeed this does point to the shortcut being bound elsewhere, and unfortunately there's not really simple way to figure it out. For some reason I remember someone saying that 1Password was intercepting one of their shortcuts in the same way. You could try exporting the shortcuts to json, modifying that shortcut, and importing it back in to see if Rectangle ends up overriding whatever is intercepting it.

**Comment by rxhanson** [comment]
Closing this one out since there's nothing that can be done Rectangle side to fix this unfortunately. Feel free to comment if anything else comes up with it.

**Comment by nmoroze** [comment]
Got here searching for people having issues with this particular shortcut. Turns out it was in fact 1Password - after quitting 1Password completely from the menu bar I was able to register Ctrl-Option-Command-L in Rectangle.  Then after restarting 1Password Rectangle seems to take precedence and the shortcut continues to work!
