### ISSUE TITLE
Exporting not working on M1 MBP 2020 MacOS Monterey 12.0.1 

### ISSUE THREAD

**Issue by karukenert** [rxhanson/Rectangle#664]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.0.1 M1 MBP 2020
Rectangle version: v0.49(54)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

Unfortunately nothing shows in the log. The saving window pops up but nothing happens if you press "Save".

edit: It does work on my 2018 MBP though, it has macOS 12.0.1 and rectangle version is the same v0.49(54)

**Comment by rxhanson** [comment]
Does the save window go away when you press save? Can you try different locations and see if it saves in some places and not others? Rectangle uses macOS save functionality out of the box, so it's odd that it wouldn't be working properly.

**Comment by fireflysemantics** [comment]
It stopped working for me completely after upgrading to Monterey ... Any ideas?

**Comment by eryno** [comment]
I came here to report that this also stopped working after upgrading to Monteray (12.1), but it actually started working again while I was typing. I'm going to write out what I observed in case it helps.

1. Upgrade to Monteray (12.1), machine reboots.
2. Nothing happens when I try to use Rectangle key commands.
3. Notice that Rectangle is not in the notification bar. I start it manually.
4. The icon appears in the notification bar. When I click the menu, all repositioning options are grayed out.
5. Check for updates, click Preferences, click About, no change. 
6. Search and find this issue, open Rectangle's menu, and all options are available as normal. Everything seems to work again.

I have no idea what happened; guess it just took a little while to spin back up. But waiting fixed it!

**Comment by eryno** [comment]
Also, I missed completely that the original issue was about exporting only 🤦🏻‍♀️ I'm not sure whether the commenter 5 days ago meant exporting or completely breaking, so I will leave my original comment for you to do with what you like, @rxhanson.

**Comment by huyz** [comment]
Save doesn't do anything either (save dialog does go away) on macOS Monterey 12.2.1 on 2021 MacBook M1 Max.

I checked System Privacy settings under Files and Folders and didn't see Rectangle listed.  I added Rectangle to Full Disk Access and restarted the app.  But that also made no difference.

**Comment by cpea2506** [comment]
This issues still open today. Anyone has any new idea? :(

**Comment by othyn** [comment]
Yep, just came across this issue today.

I open the Rectangle export dialogue, select a location to save, hit save and nothing happens. The dialogue closes as if it has saved, but no file is created.

Changing directory and doing app restarts does nothing, the functionality does not work.

macOS 12.5, M1 Pro.

**Comment by rxhanson** [comment]
There are a couple of things going on here. One of them is that there are some oddities with the macOS save/open dialog (I've experienced this type of thing outside of Rectangle, even with stock Mac apps). The other thing is that in the case of exporting not writing a file, if it's related to the logs posted by @cpea2506, then there could be a specific thing about your config that's causing this, related to how MASShortcut exposes a shortcut for serializing. In this case, it would be helpful to see what your config is - you can get it from `~/Library/Preferences/com.knollsoft.Rectangle.plist`. This is one of those things that might finally push me to switch out MASShortcut for a newer library.

**Comment by othyn** [comment]
Thanks for taking a look into it!

I maintain an OSS macOS app and settled on using [sindresorhus/KeyboardShortcuts](https://github.com/sindresorhus/KeyboardShortcuts) to implement the global keyboard shortcuts for that, although not sure if this would be any better at fixing this specific scenario. 

plist attached, although compressed to get around GitHub's file type restrictions: [com.knollsoft.Rectangle.plist.zip](https://github.com/rxhanson/Rectangle/files/9525759/com.knollsoft.Rectangle.plist.zip)

**Comment by rxhanson** [comment]
@finite-state-machine Thanks for attaching the plist. This is happening for you because some of your shortcuts are in a data format, rather than a dictionary format. 

A long time ago, I had a migration release that converted all the shortcuts from the data format to dictionary. It's possible that you could have somehow skipped over that release and kept some data format shortcuts. The easiest way around this would be to look through your plist and clear then re-record your shortcuts that are a large data chunk (the ones that are not "keyCode" & "modifierFlags" dictionary).

**Comment by rxhanson** [comment]
You won't want to convert anything to/from json.

You can just modify the plist directly if you wanted, but macOS will cache the plist so you might not see immediate results without a logout/login. Alternatively, you could use the terminal and execute `defaults remove com.knollsoft.Rectangle <KEY_WITH_DATA_VALUE>. Rather than that, though, I highly recommend just using prefs editor to delete the key-values that are data: https://apps.tempel.org/PrefsEditor/
It's free and will update the macOS cache when you edit each item.

After removing those key-values, restart Rectangle and record the shortcuts again.

**Comment by cyberdork33** [comment]
I am experiencing this export issue also. It does not appear that I have any Data formatted entries in my plist. plist is attached. I will note that in attempting to use `plutil` to convert to json format, it fails with message: `com.knollsoft.Rectangle.plist: invalid object in plist for destination format`

[plists.zip](https://github.com/rxhanson/Rectangle/files/10814495/plists.zip)

**Comment by rxhanson** [comment]
@cyberdork33 I'll be honest, nothing jumps out at me when looking at your plist. The shortcut recorder output is really the only likely candidate that has potential to cause issues like this, and one of my upcoming top priorities is switching out the shortcut recorder. I'll dig deeper in it if you still have issues after I make the switch.

**Comment by cyberdork33** [comment]
Just as a followup, I am now on Rectangle 0.68 and macOS 12.6.5 and export is working fine.

**Comment by rxhanson** [comment]
@cyberdork33 Thanks! I'm going to close this one out, and if anyone experiences this kind of issue again, then I think it's best to open a new issue and we can track it starting anew there.

**Comment by huyz** [comment]
Still doesn't work for me with v0.68.  Maybe I missed it. Was there a fix released?

**Comment by rxhanson** [comment]
@huyz can you open a new issue and include your preferences plist?

~/Library/Preferences/com.knollsoft.Rectangle.plist

**Comment by huyz** [comment]
Am I the only one that it's still happening to after upgrading to v0.68?

**Comment by huyz** [comment]
I suspect some people on this thread did the same thing I did: "Ignore Rectangle" itself. Then some time later, maybe even years later, we'd try to export but it wouldn't work.

After reinstalling and starting from scratch, one would re-set other settings such as keyboard shortcuts but probably forget about the "Ignore Rectangle" setting. Export would magically work again, but the new version of Rectangle would get undue credit for the fix ;)
