### ISSUE TITLE
modifier to allow action to work with all windows of an app

### ISSUE THREAD

**Issue by mikemccracken** [rxhanson/Rectangle#77]
I may have time sometime to work on adding this, but I'll file it in case someone else wants to do it first.

**Is your feature request related to a problem? Please describe.**

I often have many safari windows and many terminal windows, and decide I want to have a window of safari open in the left half and a window of the terminal on the right. this would be easy if I had only one window of each, but often other terminal windows are maximised and I can't just put the safari window on the left then switch to terminal and still see it.
Ideally I could just put all the safari windows on the left and all the terminal windows on the right with one shortcut per app.

(substitute top/bottom etc for left/right as you like)

**Describe the solution you'd like**

Add a global modifier key to support applying the same action to all app windows.

**Comment by rxhanson** [comment]
I may or may not consider merging this in to Rectangle depending on what this turns out to look like. My main concern is what effect this feature would have on the UI. Would you add in separate (duplicate) shortcut fields for each action you would want to to add? As in there's shortcut fields for left half, right half, and additionally added are ones for "left half all windows for app" and "right half all windows for app"? That wouldn't exactly scale nicely, and would be a significant amount of work/maintenance.

If a PR with an elegant way to incorporate this into the app is presented, I'm not opposed to it though.

**Comment by rxhanson** [comment]
I gave this a little more thought and it would require a decent amount of architecture change to the app. Currently the window movement execution is a "one time shot" per gesture execution. If this one gets implemented, it would make sense to talk through a potential solution to this before implementing it. Since I don't have plans to implement it in the near future, I'm going to close this one out. A pull request would still be welcome, though.
