### ISSUE TITLE
Way to progressively move a window across multiple monitors

### ISSUE THREAD

**Issue by mjlshen** [rxhanson/Rectangle#8]
Thanks for your work on this, I have a feature request:

It would be nice if (for example), the shortcut to move a window to the right half could be pressed again to move it to the left half of the monitor to the right (and then to the right half of that monitor, etc.), if it exists. Currently, as I understand they are separate shortcuts.

**Comment by rxhanson** [comment]
This is one that I've actually wanted to implement since I started working on this. It's what I was used to on windows 7 a long long time ago. 

Currently, Rectangle behaves identically to Spectacle on successive right and left half shortcut executions - the window will resize to 2/3 then 1/3, then back to 1/2. When this feature gets added, my thought is that there will be a checkbox to operate with this functionality instead. 

As you might suspect, I haven't added this in because I just haven't had time. PRs from anyone are welcome, otherwise it's at the mercy of my schedule :[

**Comment by rxhanson** [comment]
Alright, I got a chance to put this one in to [v0.4](https://github.com/rxhanson/Rectangle/releases/tag/v0.4). There's a checkbox in the settings for it: "Traverse screens on subsequent left or right half executions"

I don't have a way to hook up a third monitor, so I actually don't know if the screens are traversed in the correct order with three screens hooked up. If anyone can try this out and let me know, that would be great! Let me know if you come across any other issues with it.

**Comment by mjlshen** [comment]
Thanks, the screens are traversed in the correct order with three screens as well!

I've found it's a little buggy specifically with the Terminal application (it doesn't traverse windows at all for whatever reason), but I'll need to do further testing to confirm...

**Comment by rxhanson** [comment]
Thanks for letting me know!

I know what the issue is that you're seeing with terminal - the traversal is only going to work with windows that can be resized to the entire half of the screen. Terminal doesn't do that by default, and any windows that can't be resized won't do it either. I'll iterate on this and fix it up for the next release.

**Comment by rxhanson** [comment]
Ok, this should now be working properly in [v0.5](https://github.com/rxhanson/Rectangle/releases/tag/v0.5). 

In v0.5, I also added this functionality to the move left/right actions, in case you don't want your window to resize when it is moved across displays.

Let me know when you get a chance to try it out.

**Comment by mjlshen** [comment]
I can confirm it does work, thank you once again! I'm still trying to learn, but hopefully I'll be able to contribute back in the future.
