### ISSUE TITLE
Can't map a shortcut that includes the Tab key

### ISSUE THREAD

**Issue by sainathadapa** [rxhanson/Rectangle#86]
macOS version: 10.15.3
Rectangle version: 0.20 (24)

**Comment by rxhanson** [comment]
This is a restriction by MASShortcut that's most likely in place because from an input field perspective, tab is used to go the next input element in a UI. Here's the line in MASShortcut where this restriction exists: https://github.com/shpakovski/MASShortcut/blob/2ca3d08911651217d4ca5c0fe110523100040ed2/Framework/UI/MASShortcutView.m#L444

I have no plans to use a custom fork of MASShortcut in Rectangle, so in order for this to be fixed, it would have to be changed in a MASShortcut release, and then I'd pull in the latest version.

Admittedly, the wording "Allow any shortcut" in the prefs is misleading provided this restriction. 

I'm probably not going to get around to making a PR for MASShortcut in the near future, so if you strongly desire this change then my suggestion is to go ahead and make the PR for MASShortcut and I'll follow through with updating the MASShortcut version in Rectangle.

**Comment by rxhanson** [comment]
Just doing some housekeeping and closing this one out. If anyone fixes this in MASShortcut, let me know and I'll pull the latest version of MASShortcut into Rectangle.

**Comment by alecglen** [comment]
@rxhanson thanks for all your work on this project!

I was wondering, would you reconsider making the MASShortcut update mentioned above now that you are in fact maintaining a fork?

**Comment by rxhanson** [comment]
Yes, but it won't be for a while because my eventual plan is to open source my currently private Swift rewrite of MASShortcut where this was added, and use that in Rectangle instead of my Objective-C fork. My Swift rewrite has a lot of other adjustments and it will take some time to get it into a state where I'm ready to open source it. There are a lot of other tasks ahead in the queue before I will get to this, unfortunately.

[Rectangle Pro](https://rectangleapp.com/pro) (paid) uses my private MASShortcut library, and it has allowed tab for quite some time. Note that some shortcuts including tab can still not be recorded due to macOS limitations.
