### ISSUE TITLE
Custom Grid Window Layouts

### ISSUE THREAD

**Issue by ryanwwest** [rxhanson/Rectangle#89]
I love using this to split my screen into quarters or thirds, but I use a 43" monitor and sometimes I want to split each quarter horizontally in half again (or in other words, a 4x2 grid). I can imagine other desirable grid layouts for people who might use a vertical monitor (2x4), larger monitors, or more.

It would be really neat to be able to define a grid for a given monitor and have shortcuts that fix windows to different parts of the grid (in addition to the default options). Perhaps you could cycle the window through different positions on the grid.

This isn't intended to be a feature request as it would probably be quite difficult to actually implement; the source code shows a different Swift file for each support layout as is so I'm not asking for this. Maybe I'll try to implement it myself eventually. I just couldn't find another good place for a discussion on the topic (if there's a better place, let me know).

**Comment by rxhanson** [comment]
See https://github.com/rxhanson/Rectangle/issues/7

In terms of a place to have discussions on topics, it's pretty annoying that GitHub doesn't have a straightforward place dedicated to it. Issues carry the implication that there's something that must be done. I'll see if I can find a proper place for discussion because it's definitely necessary. Gonna close this one out, and I'll comment back when I've figured out what I want to do for discussions.
