### ISSUE TITLE
Cannot map ⌥⌘H

### ISSUE THREAD

**Issue by sickill** [rxhanson/Rectangle#9]
I prefer to use ⌥⌘H / ⌥⌘J / ⌥⌘K / ⌥⌘L for "Left/Right/Top/Bottom Half" commands, and while I was able to remap to ⌥⌘J / ⌥⌘K / ⌥⌘L I'm not able to remap "Left Half" to ⌥⌘H. Getting this error:

```
The key combination ⌥⌘H cannot be used
This shortcut cannot be used because it is already used by the menu item ‘Hide Others’.
```

It seems that Hide Others command is mapped implicitly, without a option for changing it.
Is there a way to unmap ⌥⌘H via a config file? Also, are there any other "hidden" mappings? I couldn't find any list of them, and I found ⌥⌘H in the source code by doing search for "Hide Others" on GH.

Rectangle 0.3 (5)
macOS Mojave 10.14.6

**Comment by rxhanson** [comment]
Right, ⌥⌘H is being used by the menu item "Hide Others" as you found out. The menu item isn't seen during normal use, since Rectangle is a menu bar app. You can find this menu item and others that would conflict with keyboard shortcut usage in the Main.storyboard if you load up the project in Xcode. These menu items just use default keyboard shortcuts that are commonly used in other apps. There's nothing else in terms of "hidden" mappings.

If you're looking for a quick fix for this that you could throw in on your own and run, there's a couple ways to go about it. The easiest would be to just go in and remove that menu item in the Main.storyboard file. Alternatively, you could force the keyboard shortcut recorder allow any shortcut, even if it is used in a menu item. See https://github.com/rxhanson/Rectangle/issues/5.

The fix I will likely put in is a toggle setting that allows any keyboard shortcut to be used, even if it is already used elsewhere. It might take me a few days to get to it, though.

Since ⌥⌘H is commonly used for "hide others" in apps (it's an Apple default for new apps in Xcode), the default behavior of preventing this keyboard shortcut from being used still makes sense to me. It also still makes sense to me to leave the menu item in Rectangle.

**Comment by rxhanson** [comment]
Alright, finally got around to pushing out another release. [Version 0.4](https://github.com/rxhanson/Rectangle/releases/tag/v0.4) now has a checkbox in the settings tab of the preferences pane for allowing any keyboard shortcut. This will allow you to record ⌥⌘H, or any other shortcut.

**Comment by sickill** [comment]
Works like a charm, many thanks!

**Comment by flyfishMT** [comment]
Is a similar system mapping the reason I can't map ^⌥H

**Comment by rxhanson** [comment]
@uoziod what this thread is saying is that to allow that shortcut, you have to check a box in the gear tab to "remove the shortcut recorder restrictions". There is no downgrade necessary.

**Comment by uoziod** [comment]
@rxhanson, indeed! I feel stupid 😁 
Sorry for being abrupt and thank you for such a useful tool
