### ISSUE TITLE
Change focus feature

### ISSUE THREAD

**Issue by Matlino** [rxhanson/Rectangle#91]
Let's say I have three windows visible on the screen, one next to each other. I would like to change the focus between them with a shortcut. For example, I could user CMD+1, CMD+2 and CMD+3 to change focus between those three windows. 

I see that Rectangle is not accepting any new feature requests right now. But this seems to me as very basic and handy functionality. And It's not possible in any windows manager on mac AFAIK. So I thought I would just leave this here for anybody who knows swift and would like to implement it.

**Comment by rxhanson** [comment]
I like this idea, but it's not something I would look to roll into Rectangle, even if there is a fork with it available. (The main reason for not taking more feature requests is to keep Rectangle as simple as I can - I'm certain that's why so many people like Spectacle and Magnet).

I actually think this feature as a standalone app would be an awesome first open source swift project for someone to implement.

**Comment by marcpm** [comment]
@Matlino While not perfect, you can set a shortcut to cycle focus through all windows on a screen, in macOS's  SystemPreferences > Keyboard > Shortcuts> Keyboard > "Move focus to active or next window"
