### ISSUE TITLE
Restore window size when window is moved

### ISSUE THREAD

**Issue by FezVrasta** [rxhanson/Rectangle#92]
Hi, I understand you don't accept feature requests, but I'll leave it here in case someone feels like to implement it.

Something I miss from Magnet is the following behavior:

1. Use any shortcut to resize/position a window;
2. Drag the window somewhere;
3. The window size is restored to the size it used to have before it was resized by the software;

**Comment by rxhanson** [comment]
This is actually a bug. This functionality is/was in Rectangle but there's a regression that causes it to not always happen anymore.

**Comment by rxhanson** [comment]
When you get a chance, can you try out v0.21 with the fix?https://github.com/rxhanson/Rectangle/releases/tag/v0.21

If everything looks good, I'll post it to the update channel.

**Comment by FezVrasta** [comment]
That was quick!

It works, but there's some delay (~1 second)

**Comment by rxhanson** [comment]
Thanks for trying it out quick. I noticed that delay, too. It seems like the delay is not as noticeable after I've used it for a little bit of time. It could be some macOS weirdness, but I'll see if there's anything I can do about it. 

The issue was actually due to something changing in macOS - nothing changed Rectangle side that could have broken this. I just tried in Magnet and it appeared to have the same bug for me.

**Comment by rxhanson** [comment]
Alright, round 2:
https://github.com/rxhanson/Rectangle/releases/tag/v0.22

Let me know how this one goes.

**Comment by FezVrasta** [comment]
0.22 seems much better, thank you a lot!

**Comment by hmarr** [comment]
Is there a way of disabling this behaviour, by any chance?

**Comment by rxhanson** [comment]
@hmarr There's not, but I'd be willing to accept a PR that makes this configurable via Terminal command.

**Comment by jakeswork** [comment]
Was this behaviour put into some sort of toggle? It's not working for me on v0.46

**Comment by rxhanson** [comment]
@jakeswork The checkbox is "Restore window size when unsnapped" in the settings tab
