### ISSUE TITLE
Crashing on latest Ventura beta

### ISSUE THREAD

**Issue by krubenok** [rxhanson/Rectangle#920]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.0
Rectangle version: 0.59
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): n/a App Crashes before menu is available. 

In the last week or so, Rectangle has consistently crashed (activity monitor reporting as "Not Responding") on my Ventura beta machine. The menu bar applet never appears, no do any of the hotkeys function.

Happy to provide additional logs if something specific would be helpful.

**Comment by rxhanson** [comment]
Thanks for reporting. Are there any Crash Reports or Spin Reports for Rectangle in the Console app?

**Comment by krubenok** [comment]
Not that I can see, the only console message pertaining to Rectangle is `LSExceptions shared instance invalidated for timeout.`

**Comment by rxhanson** [comment]
Without a Crash or Spin report, there's not much I can do, since I cannot reproduce it.

You can try: 

1. Removing it from System Preferences  → Security & Privacy → Privacy → Accessibility, then relaunching it. Ventura has changed some of this behavior so it could be a Ventura bug.

2. Deleting the prefs using a Terminal command and see if it was something weird with your config:

`defaults delete com.knollsoft.Rectangle`

**Comment by krubenok** [comment]
Deleting the prefs seem to have done the job! I'll close this out assuming it was some weird one-off with my particular env, but will reopen if it comes back later...
