### ISSUE TITLE
Rectangle app seems to be ignoring/disabled for Chrome

### ISSUE THREAD

**Issue by 12pm30** [rxhanson/Rectangle#921]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.5.1
Rectangle version: Version 0.59 (65)

When I go to chrome and open up Rectangle menu, all the keystrokes are disabled while `Ignore Google Chrome` is unchecked.
<img width="290" alt="Screen Shot 2022-09-13 at 4 54 38 PM" src="https://user-images.githubusercontent.com/16752491/190007249-1e6bcb1b-f1a7-4456-a8aa-d227ba8d70eb.png">

**Comment by thejae** [comment]
I have a variation of this issue. Chrome doesn't maximize on the built-in MacBook display.

Setup:
1 MacBook pro + 2 external screens

Problem:
1. Rectangle works for chrome on all external displays.
2. For MacBook's built-in display, rectangle does not maximize Chrome (neither does dragging Chrome to the top of the screen nor using keyboard shortcut) - however all other resizing works and correctly triggers the overlay guide.

macOS Monterey 12.6 (21G115)
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)

**Comment by rxhanson** [comment]
@12pm30 this means that Chrome is not working with the Accessibility API in macOS, and it likely needs to be closed and relaunched (sorry, this is something that's outside the control of Rectangle). If this problem persists, it'd have to be addressed Chrome side.

@thejae Please create a new issue rather than adding to a semi-related issue.
