### ISSUE TITLE
Can this be hosted somewhere more secure?

### ISSUE THREAD

**Issue by MDJCM** [rxhanson/Rectangle#95]
Since this app requests accessibility clearance, it's a bit dodgy that it's hosted on random hosting. I'm guessing a hacked DMG would not be trivial to detect by the website owner.

**Comment by rxhanson** [comment]
Random hosting? Can you specify what's random?

**Comment by rxhanson** [comment]
The following are safe locations to download the app:

https://rectangleapp.com
https://github.com/rxhanson/Rectangle/releases 
brew cask
in-app update
https://macupdate.com (points to https://rectangleapp.com)

If anyone comes across other places where they find the app, let me know and I'll see if it's possible to request a takedown.

**Comment by MDJCM** [comment]
I meant that we've seen it before that even established companies can fail to detect hacks to their servers for some time, and it would be smart of a hacker to replace the DMG available via your site with one infected. The user then gives it accessibility permissions. Game over. So it would be re-assuring to have the DMG available via a more secure source. But I guess for now the github release is one way to do it.

**Comment by rxhanson** [comment]
Alright, so the concern here is "I don't trust the developer to keep https://rectangleapp.com secure." I realize that there is an element of trust that all users must bestow on an app developer such as myself, and I take it seriously. 

At the end of the day, the only way to really be 100% safe is to download the source (and scan through the source for anything questionable) and build/sign the app yourself for your personal use. 

Let's go through this a little more piece by piece, starting with the .app itself. The .app is notarized by Apple using my Apple developer credentials. Notarizing is Apple's way of saying "we scanned this app for malicious code and didn't find anything at this time". If a notarized .app is modified, macOS will put up some guards to prevent users from casually installing it. I've taken a look down this path because people pirate cracked versions of my app, Multitouch. A user could bypass the macOS guards and force install/run a modified .app, but a smart person would not do this under any circumstance. Apple is going to start (and maybe has already started?) preventing non-notarized apps from being installed at all - which means no more Spectacle and a lot of other apps that stopped being maintained before notarization was introduced by Apple. 

In terms of actually running the app, another safeguard you could have in place is Little Snitch. The concern with accessibility authorized apps is that they could keylog. Rectangle reaches out to the internet for updates if automatic updates are enabled, or if you check for updates manually. It does not reach out to the internet any other time, so if you are a concerned user then you can run Little Snitch to make sure there are no other communications to the outside world.

Let's go back to the website, rectangleapp.com. The site is https, so it's using SSL certs to guarantee that you are at least getting a download from the expected place. Your concern is that someone could get access to the deployment of the website, and replace the dmg with a hacked copy. Since I am the only person that has credentials to deploy code to this site, then I am the most likely weakest link in the chain, aside from the service that I use to host the site. As a developer, I could make mistakes that makes the site more vulnerable to attackers, but there's not really a way for someone to gain access to site deployment without my credentials (it's not a wordpress site with a web admin console, or something of the like). So then, how much do you trust me to not somehow let my credentials get stolen and used with 2fa for the specific purpose of uploading a hacked dmg?  For better or worse, I'm just one guy. Nobody else has the credentials - which is different from a larger company where credentials might have to get passed around between a handful of people. Also, the service that I use for hosting the site is a popular choice, and obviously their business would be at risk if they were not providing a secure hosting platform. 

Last, what about downloading the release from GitHub. This also has the same weak link as the website - my credentials (GitHub in this case). GitHub doesn't require 2fa, but I do have it enabled. 

Yes, there is risk in downloading any app or software from anywhere as opposed to taking source you trust and building it (even on the Mac App Store, there's risk). At least Apple is a security focused platform and notarization is in place to help prevent average joe from compromising himself.

**Comment by rxhanson** [comment]
Small update on this. I have now shifted all dmg hosting to point to the releases in GitHub. This is just a cost-saving measure now that Rectangle gets enough downloads to make hosting more expensive than I was willing to pay. I was hosting the dmg on rectangleapp.com to have some faster download speeds, but it looks like GitHub download speeds have improved recently, making hosting on rectangleapp.com unnecessary.

**Comment by darboscalante** [comment]
Hello. I've downloaded your great app a few of days ago. Thanks for it, really amazing. Now I have this problem: my Facebook Business Account has been hacked repeatedly from around those days, even I have this 2FA activated from long ago. The reason I'm here today is just for asking some advice about how can I be sure your App is still safe. I really don't want to affect you or your incredible app. I'm just looking for something that can assure me where do I need to look. Thanks in advance

**Comment by rxhanson** [comment]
@darboscalante To sum up this thread: as long as you downloaded Rectangle from https://rectangleapp.com (which points to this repo) or directly here on this Github repo, then you don't have to worry about Rectangle. The app is notarized with my developer id, and if for some reason you downloaded a tampered version of the app, then you would have to bypass gatekeeper to install it. Do not bypass gatekeeper to install any app. I understand when something bad happens you want to try to tie up all loose ends, but I recommend looking elsewhere if you downloaded Rectangle from here and didn't have to bypass Gatekeeper to install it.
