### ISSUE TITLE
Maximum "Stage Manager recent apps area" value is too small

### ISSUE THREAD

**Issue by hsjunn** [rxhanson/Rectangle#981]
- [X] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Ventura 13.0
Rectangle version: 0.61 (67)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): N/A

In my iMac Pro 2017 with the "default" display resolution settings, Stage Manager uses 214 pixels for its recent apps area,
which is larger than the current maximum value allowed by Rectangles i.e., 200.
Could you please increase the maximum value?

My current (working) workaround is:
- export the preferences to json
- manually edit the "stageSize" float value
- save
- import the edited json

edit: I understand Rectangles doesn't need to exactly replicate that value, but I feel sorta compulsive about that.

**Comment by rxhanson** [comment]
Agreed. I'll slate this for the next release.

**Comment by YouRik** [comment]
I think an tick box option to always keep the space for stage manager would be nice, not only when there are recent apps in the stage manager area.
I'm suggesting this because when you have a window A maximized, then open a new window B, window A gets moved into the miniature view. When you then switch back to A, the stage manager area is hidden because A has not resized to account for the stage manager area and B gets completely hidden, so it's necessary to resize A manually.

**Comment by rxhanson** [comment]
@YouRik The way to achieve what you're after is just to set a screen edge gap, using a terminal command (and restart the app):
https://github.com/rxhanson/Rectangle/blob/master/TerminalCommands.md#setting-gaps-at-the-screen-edges

Then set stage manager recent apps area to 0.

Closing this one out since it was merged a while back.

**Comment by YouRik** [comment]
> @YouRik The way to achieve what you're after is just to set a screen edge gap, using a terminal command (and restart the app): https://github.com/rxhanson/Rectangle/blob/master/TerminalCommands.md#setting-gaps-at-the-screen-edges
> 
> Then set stage manager recent apps area to 0.
> 
> Closing this one out since it was merged a while back.

Thank you, I was not aware of the advanced settings through the terminal.
